### ISSUE TITLE
Is FreeImage is GPL compatible now?

### ISSUE THREAD

**Issue by timofonic** [eXeC64/imv#102]
Please see [Alternatives for FreeImage](https://github.com/imageio/imageio/issues/114). It seems to be solved, but no idea how and where's the updated code with that new license.

**Comment by eXeC64** [comment]
GPL compatible? It's GPL licensed: http://freeimage.sourceforge.net/license.html
and has been used under the GPL since imv was created.

Can you clarify what this issue is asking please?

**Comment by timofonic** [comment]
Oh sorry, I did read an old issue with some project using it. Sorry.

2016-12-28 14:37 GMT+01:00 Harry Jeffery <notifications@github.com>:

**Comment by eXeC64** [comment]
No worries
