### ISSUE TITLE
Fullscreen exits when changing focus

### ISSUE THREAD

**Issue by beanaroo** [eXeC64/imv#103]
When presenting using imv fullscreen on one monitor, it exits fullscreen as soon as the focus changes (i.e. a window on another display). This is inconsistent with how full screen works on all other applications, so I'm not sure if it's expected behaviour.

I am running i3 window manager and imv v2.1.3

**Comment by eXeC64** [comment]
Thanks for the report. I use i3 as well, but unfortunately don't have multiple monitors available at the moment, so I can't reproduce this.

The behaviour you're describing is coming from SDL, the library we use for handling the window. My best guess at present is either a bug in SDL, or we're using a [fullscreen mode](https://github.com/eXeC64/imv/blob/master/src/viewport.c#L41) that does not match your expectations of how it should behave.

**Comment by yxord** [comment]
This might be related to the default SDL2 behavior of minimizing any fullscreen windows on focus loss. You could try disabling that manually and see whether it works as expected.
`SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS=0 imv`

**Comment by beanaroo** [comment]
Thanks, @yxord. That does work!

**Comment by eXeC64** [comment]
Nice find @yxord, thanks. That's definitely undesirable behaviour for imv. I'll make that fix in the next release of imv.

**Comment by czarkoff** [comment]
@eXeC64, I'd warn you against such change. IMO we should refer people to appropriate documentation instead and stick to whatever happens by default in SDL2.

**Comment by eXeC64** [comment]
I'll add a config option to maintain fullscreen on focus loss. Seems like a reasonable compromise without requiring our users to be familiar with SDL.
