### ISSUE TITLE
OpenGL Warning when running in VirtualBox VM

### ISSUE THREAD

**Issue by neolee** [eXeC64/imv#105]
Ubuntu 16.10 (4.8.0-44-generic x86_64) running in VirtualBox (host OS is macOS).

When opening a image (it does show correctly) the following warning occurs:

> OpenGL Warning: Assertion failed: obj=0, file /mnt/tinderbox/add-5.1/src/VBox/Additions/common/crOpenGL/pack/packspu_glsl.c, line 210

Any suggestion?

BTW, thanks for bring us xmonad users such an amazing tool.

**Comment by eXeC64** [comment]
Thanks for the report, but I'm afraid I'm none the wiser. Given that the Window and all OpenGL calls are handled by SDL2, it's highly likely this is an issue with SDL2, not imv.

**Comment by eXeC64** [comment]
Closing as is not suspected to be an issue with imv, but either SDL2 or VirtualBox.
