### ISSUE TITLE
Document package names for Ubuntu build

### ISSUE THREAD

**Issue by tbnorth** [eXeC64/imv#106]
Ubuntu install would be a lot easier if you could list package names to install for dependencies.  I *think* it's just

```
sudo apt install libsdl2-dev libfreeimage-dev libsdl2-ttf-dev
```

for 16.04 LTS, but that should really be confirmed on a clean Ubuntu install.

**Comment by eXeC64** [comment]
I'm afraid I'm not an ubuntu user so I can't confirm this. If someone else can, this seems like a reasonable thing to add to the Install section of the README.

**Comment by wokka1** [comment]
While not ubuntu, I'm installing this on raspbian-jessie and ran into the same issues.  For this release, I used the following on a clean install:

`sudo apt install libsdl2-dev libfreeimage-dev libsdl2-ttf-dev libfreeimage3 libfontconfig1-dev`

**Comment by eXeC64** [comment]
Thanks. I'll get these added to the README.

**Comment by eXeC64** [comment]
Fixed, finally.
