### ISSUE TITLE
Exiting one imv window close multiple imv window

### ISSUE THREAD

**Issue by n3f4s** [eXeC64/imv#109]
Hi,

I'm using i3 window manager.
When closing (in ``i3``) a window, the focus goes to the last focused windows. For example, if the focus is on window 1, I switch to window 2 and close it, the focus will go back to window 1 even if window 2 and 2 were not adjacent.

When closing an ``imv`` window (with ``q``), if the last focused window was also an ``imv`` window, it will be closed too (without having pressed ``q`` again). If the window that acquire the focus (after the two first windows are closed) is an ``imv`` window too, it will be closed (without having pressed ``q`` again).
Like this, one keystroke on ``q`` can close multiple (more than 3) ``imv`` windows.

The ``imv`` windows are opened completely independently and should not be closed by one keystroke (it should only close the currently focused window).

``imv`` is the only soft that I've seen showing this behaviour so it doesn't look like it's a bug from ``i3``.

This bug look a bit like the one I've described in issue #108, but in doubt, I've chosen to file two issues.

**Comment by eXeC64** [comment]
Just reproduced this on my machine. I'll work on this for v3. Thanks!

**Comment by eXeC64** [comment]
Fixed in c51dff6a4e5bd21491bb0c085cb08f35275332a0
