### ISSUE TITLE
textual overlay

### ISSUE THREAD

**Issue by wokka1** [eXeC64/imv#110]
the -d option for textual overlay works well for full screen slideshow, but an option to customize what is shown would be beneficial.  

I'm actually after a way to show the filename but nothing else on the overlay.

Thanks!

**Comment by eXeC64** [comment]
This is planned. V3 of imv will include support for a configuration file to customise keybindings and the contents of the window title and text overlay.

**Comment by eXeC64** [comment]
Config file support has been added, the only thing needed for this now is a config option to control the overlay's text
