### ISSUE TITLE
Add the ability to bind particular buttons to scripts that act on the active selection

### ISSUE THREAD

**Issue by michaelmrose** [eXeC64/imv#115]
you can do something similar with a script so long as you decide to run said script ahead of time with a particular singular action in mind but binding keys lets you decide to do operations after you are merely viewing a list of files.

You could decide to delete some, set one as a wallpaper, edit another in gimp etc etc.

I find this functionality much more useful.

**Comment by eXeC64** [comment]
This functionality is intended as part of #57 - there's already basic support internally for commands. The ability to run a command on the currently selected file is a feature I want to implement for v3. I've also found the `p` bind insufficient for my needs.

**Comment by eXeC64** [comment]
Support for this has been added
