### ISSUE TITLE
(enhancement?) always open in slideshow

### ISSUE THREAD

**Issue by ROMSY-SAN** [eXeC64/imv#117]
Hi, i using imv as an alternative to feh because your app supports gif 👍 
The only problem i've got right now is, when i open a image in a folder it opens only that one image in that folder. Usually i am ok with that, but sometimes i need to open a picture inside of a folder and scroll from that point the rest of the images like a slideshow. is there any intention to add that future, so i can set it up as standard config and browse everytime a slideshow from a specific point from my folder?

**Comment by eXeC64** [comment]
One way you could do this is tell imv to open the entire directory by specifying the directory the image is in, and then use the `-n` argument to specify the starting image. `-n` accepts either a number, or the path of the image to start on. So: `imv -n $FILE $(dirname $FILE)` ought to open the entire directory, starting with `$FILE`.

**Comment by ROMSY-SAN** [comment]
usually i open pictures with ranger. the idea was more like go into a directory, open the picture and then start from there the slideshow in both directions. actually besides gifs this is for me the most important feature in a image viewer.

**Comment by eXeC64** [comment]
That's what the command I suggested does. It opens the given image, whilst allowing you to view the other images in the directory via arrow keys.

Closing as this is already supported so far as I can tell.

**Comment by Kommynct** [comment]
I'm trying to figure out how to make this the default via the .desktop file with the whole exec= section, i don't mean to bother anyone but i can't figure it out for the life of me, this is the only thing keeping this image viewer from being perfect for me, thank you if you could help

**Comment by Slider-Whistle** [comment]
@Kommynct `imv -n %U $(pwd)`
