### ISSUE TITLE
imv opening with a 1280x720 resolution even when the image is smaller than that

### ISSUE THREAD

**Issue by leewdch** [eXeC64/imv#122]
I'm using `imv -s <image.gif>` to open GIFs but the window dimensions are incorrectly assigned for images smaller than 1280x720. I thought this was an i3wm issue that was causing the image to be wrapped incorrectly but [somebody](https://github.com/i3/i3/issues/3091#issuecomment-352208112) suggested me that this might be an imv issue since that specific resolution is hardcoded inside imv when an image is opened.

This is the hardcoded line I'm talking about: https://github.com/eXeC64/imv/blob/68b78734bba844671df36a4a993b15cd3a7150ed/src/imv.c#L152

**Comment by eXeC64** [comment]
Hmm, I've never hit this before as imv was never envisaged for floating-window use, primarily tiled. However, it shouldn't be hard to fix.

Would an option for imv to automatically resize its window to fit the current image solve your use case suitably?

**Comment by hhiru** [comment]
that would be great but this should fix the issue for images smaller than 1280x720, what if the image is greater? I have a setting in my i3wm config that forces floating windows to never be greater than 960x540, in that case the window should both wrap the image size AND resize said image to fit the i3wm floating window dimensions. is this already possible with the `-s` option?

**Comment by eXeC64** [comment]
Can you try imv with the https://github.com/eXeC64/imv/tree/auto-resize branch?

Be aware that for v3 some of the flags have changed (including `-s` usage) - see the man page for details on what the options are. With the `-w` option imv will automatically resize its window to the same dimensions of each image it loads.

Let me know if this works for you, and I can include it in the next release.

**Comment by hhiru** [comment]
I tried installing the new branch but I have this error when trying to opening an image
> Unknown argument 'w'. Aborting.

**Comment by eXeC64** [comment]
Looks like you're on cfafe6d - the master branch, not 7f2893a which has the fix.
Correct version with the fix is `imv v3.0.0-rc1-7-g7f2893a`

**Comment by eXeC64** [comment]
@hhiru Any luck?

**Comment by hhiru** [comment]
sorry if I waited so long for replying. I have an issue when I try to compile the autoresize branch:

> $ sudo make
> cc -c -W -Wall -pedantic -Wmissing-prototypes -std=c99 -DIMV_VERSION=\""v3.0.0-rc1-7-ga65b30b"\" -I/usr/include/SDL2 -D_REENTRANT -D_XOPEN_SOURCE=700 -o build/loader.o src/loader.c
> src/loader.c:9:10: fatal error: FreeImage.h: No such file or directory
>  #include <FreeImage.h>
>           ^~~~~~~~~~~~~
> compilation terminated.
> make: *** [Makefile:41: build/loader.o] Error 1

**Comment by eXeC64** [comment]
`imv v3.0.0-rc1-7-ga65b30b` is the master branch. The auto-resize branch will have the version string `imv v3.0.0-rc1-7-g7f2893a`.

This downloads and builds the auto-resize branch:
```
git clone git@github.com:eXeC64/imv && cd imv && git checkout auto-resize && ./build/imv -h
```

**Comment by hhiru** [comment]
It works but it forces the window in the top left corner. Is it possible to center it?

**Comment by vilhalmer** [comment]
Any chance of bringing this back from the dead? The window positioning isn't a blocker for me, I can manipulate it from the window manager side.

**Comment by eXeC64** [comment]
I'm happy to take another go at this. What's the preference for behaviour?
I'm thinking of making the following changes:

1) By default, resize to match the first image
2) Add an option to enable auto-resizing whenever a new image is opened.
3) Add an option to allow auto-recenter the window when it's auto-resized

Is the suitable, or would something else be preferable?

**Comment by vilhalmer** [comment]
That all sounds good to me!
