### ISSUE TITLE
Config file location doesn't follow the XDG spec

### ISSUE THREAD

**Issue by raku-cat** [eXeC64/imv#124]
The current code is set to look in $XDG_CONFIG_HOME/imv/config but never $HOME/.config/imv/config
The spec states if $XDG_CONFIG_HOME is unset that programs should fall back to $HOME/.config https://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables

**Comment by eXeC64** [comment]
Good catch, thanks
