### ISSUE TITLE
[Feature Request] Combine commands

### ISSUE THREAD

**Issue by chocolateboy** [eXeC64/imv#130]
<table>
    <tr><th>imv</th><td>v3.0.0</td></tr>
    <tr><th>OS</th><td>Linux (Arch)</td></tr>
</table>

**keywords**: bind, binds, compose commands, combine commands, multiple commands, multiple statements

It would be great if there was a way to combine commands e.g. to configure <kbd>p</kbd> to print out the filename (`exec echo $imv_current_file`) *and* navigate to the next image (`select_rel 1`) rather than having to press <kbd>p</kbd> followed by <kbd>→</kbd> or <kbd>]</kbd> every time, which is much slower.

**Comment by Jeinzi** [comment]
I would like such a functionality, too. A few weeks ago, I tried to configure <kbd>X</kbd> to delete the current image and switch to the next one, but I didn't find a way to realize that.

**Comment by eXeC64** [comment]
Fix merged, will be part of v3.1.0
