### ISSUE TITLE
Fails to build on GNU/Hurd: no PATH_MAX

### ISSUE THREAD

**Issue by paride** [eXeC64/imv#132]
imv fails to build on GNU/Hurd because `PATH_MAX` it not defined:
```
> src/loader.c:168:13: error: 'PATH_MAX' undeclared (first use in this function); did you mean 'NAME_MAX'?
```
For the complete build log see https://buildd.debian.org/status/package.php?p=imv. `PATH_MAX` is used in `imv.c`, `loader.c`, `navigator.c`. The Hurd has no hard `PATH_MAX`; best practice is to allocate dynamic buffers based on `pathconf(..., _PC_PATH_MAX)`. This would be the best solution, however it's also common to supply a fallback constant after including `limits.h`, e.g.
```
/* GNU/Hurd has no hard PATH_MAX */
#if defined(__GNU__)
#define PATH_MAX 4096
#endif
```
Could you please take a look?

Thanks!

**Comment by eXeC64** [comment]
Resolved, but used `IFNDEF PATH_MAX` so the fix is available to non-Hurd systems with this quirk.
