### ISSUE TITLE
Add more RAW formats

### ISSUE THREAD

**Issue by notramo** [eXeC64/imv#133]
Could you use the RAW format decoding library of [Rawtherapee](https://github.com/Beep6581/RawTherapee)?
It should also cache the decoded RAW images for loading faster next time.

**Comment by eXeC64** [comment]
Supporting multiple backends for decoding images is something I'd like to have in the future, but haven't had the time or impulse to work on yet. Is there a particular RAW format you're missing?

Getting FreeImage to add support for that format is another way you can get this in imv without waiting on me.
