### ISSUE TITLE
Native wayland?

### ISSUE THREAD

**Issue by freed00m** [eXeC64/imv#140]
Hi,

lots of mention about being for wayland but it starts in Xwayland.

How to run it in native wayland? No mention in github or man page

If it can't please remove the wayland from title 
`Image viewer for X11 and Wayland`

**Comment by eXeC64** [comment]
Can you try setting the env variable, `SDL_VIDEODRIVER=wayland`. SDL2 is used for input and window management, and is responsible for using either X or Wayland on your system.

I'll add this to the documentation.

**Comment by freed00m** [comment]
Yes that worked, thank you very much.

For those who use systemd you can use the `~/.config/environment.d/profile.conf` file and set the variable there, withtout the export keyword. :)
