### ISSUE TITLE
Long path lists from stdin are arbitrarily truncated

### ISSUE THREAD

**Issue by foghawk** [eXeC64/imv#141]
I have a directory with a large number of files which I want to view. However, when I try piping a list to imv's stdin, imv shows only ~100–300 files (with the exact number changing every run), ignoring the rest. 

I have confirmed that lists are correct (and that no item is longer than `PATH_MAX`) before being passed to imv. OS is Arch Linux 4.20.

`imv -r` isn't a useful alternative here since it always uses storage order (as `find`); I want to sort by filename, which has to be done externally.

**Comment by eXeC64** [comment]
I've noticed this before but never looked into it. I suspect it's a race conditioning on how `stdin` is handled.
