### ISSUE TITLE
Cannot bind Escape

### ISSUE THREAD

**Issue by schauveau** [eXeC64/imv#147]
I am trying to bind `<Escape>` to the `quit` command but that key seems to be ignored. 

I tried 3.0.0-1 from Debian and also the current git master.

**Comment by Jeinzi** [comment]
I can reproduce this with
- Arch Linux 4.20.12-arch1-1-ARCH
- i3
- imv 3.0.0-3 from the repos

**Comment by schauveau** [comment]
I tracked the issue to the imv_bin_handle_event function (in src/bind.c) where the SDLK_ESCAPE is manually handled to call imv_bind_clear_input.  The purpose of that is unclear to me. After commenting out that piece of code, my Escape binding is now working.

**Comment by eXeC64** [comment]
Yes, I've already got a patch for this. I just haven't yet pushed it to github.

The purpose of the Escape builtin was a way to get out of a partial bind state. The patch I have changes it to be hitting escape twice, which fixes Escape being unbindable with the caveat that <Escape><Escape> isn't a bindable keysequence, but that's a very unlikely scenario.

Thanks for the bug report, I'm surprised this went unnoticed for so long.

**Comment by schauveau** [comment]
While browsing through the code I noticed that binding ; (SEMICOLON) is probably not possible either because the `break` in ivm.c is outside the body of the `if (event->key.keysym.mod & KMOD_SHIFT)'

**Comment by eXeC64** [comment]
Good catch. I'll put in a fix for that too.
