### ISSUE TITLE
Overlay text is blurry

### ISSUE THREAD

**Issue by nostdm** [eXeC64/imv#148]
**Operating system:** Arch Linux 4.20.12-arch1-1-ARCH
**Compositor:** Sway version 1.0-rc1-92-gbe0588ef
**Version:** 3.0.0-3

The overlay text seems blurry compared to other text on the system. I'm not sure if this is due to HiDPI scaling on sway or whether there's a problem with `imv` rendering the text. I tried multiple fonts with the same result.

**Update:** There's a known issue on `sway` where the XWayland applications are not scaled properly on HiDPI displays. And indeed setting the scale to 1 seems to eliminate the blurriness from the overlay. This would suggest that `imv` runs as an XWayland application and not Wayland native. Is there a way to tell `imv` to run as a Wayland native application?

**Comment by eXeC64** [comment]
Yes, SDL defaults to X still but see #140 for how to set default to native Wayland.

**Comment by nostdm** [comment]
It seems that it didn't work, these the Wayland related variables exported on my system:
```
export GDK_BACKEND=wayland
export EGL_PLATFORM=wayland
export CLUTTER_BACKEND=wayland
export QT_QPA_PLATFORM=wayland-egl
export QT_WAYLAND_FORCE_DPI=physical
export SDL_VIDEODRIVER=wayland
```
Despite that `imv` still starts as an X11 aplication.

**Comment by eXeC64** [comment]
Okay. So you no longer think it's a wayland issue?

Can you take a screenshot demonstrating the issue, and indicate what scale value you're using in sway?

**Comment by nostdm** [comment]
Here's a side-by-side comparison, on the left text in a wayland terminal window, on the right, a screenshot of the text with overlay text on top, both of which are more fuzzy/blurry than regular text:

![image](https://user-images.githubusercontent.com/16334589/53675169-d26d2600-3c8b-11e9-9748-4141991fa314.png)

**Comment by eXeC64** [comment]
Thanks for the screenshot. I'll mess with my own scaling settings, have a play and see if I can get to the bottom of this.

**Comment by Yaroslav-95** [comment]
I also have the same problem when scaling is set under Sway. What I have noticed is that imv unnecesarily scales the image, so the image looks blurry as well, and doesn't make use of the high resolution display. I can also confirm that it is running as a native Wayland client and not under XWayland (tested by using xeyes).

It is really a shame, since I have yet to find a simple image viewer that works fine with display scaling for Wayland, and looking at blurry images kind of defeats the purpose of a hires display.

**Comment by eXeC64** [comment]
I've done some digging on this issue this evening, and the underlying window library imv uses, SDL, does have a hidpi mode. However, as of yet it's not implemented for Wayland. Seemingly only windows/osx.

I had a play with SDL itself and I've got a buggy WIP patch that adds hidpi support for wayland, but it needs more work still. Plus imv needs further tweaks to properly handle the mismatch between window  coordinates and scaled rendering coordinates.

**Comment by eXeC64** [comment]
Turns out someone else has already solved the issue in SDL here: https://bugzilla.libsdl.org/show_bug.cgi?id=4521

It works nicely on my system with the patch applied. Only work needed on this issue is fixing imv's handling of the viewport.
