### ISSUE TITLE
Key binds doesn't use my keyboard layout

### ISSUE THREAD

**Issue by skielred** [eXeC64/imv#153]
My keyboard layout is French AZERTY, the A key is where the Q key is on a QWERTY keyboard, so by default to quit I have to press A instead of Q which isn't very intuitive.

I can fix this by adding
```ini
[binds]
a = quit
```
to my config file, however native support of the keyboard layout would be welcomed.

I'm using Wayland / Sway.

The environment variable `XKB_DEFAULT_LAYOUT` is set to `fr,us` (set from Sway).

**Comment by eXeC64** [comment]
This is strange, I'd expect imv to respect your keyboard layout. If you hit `:` to start entering a command, is your keyboard layout respected when typing text?

**Comment by skielred** [comment]
Commands use the AZERTY layout correctly.

However I had to type an uppercase `M` instead of `:`, the **m** being where the **:** is on a French keyboard.

The bug doesn't occur in other programs launched in Wayland.

**Comment by eXeC64** [comment]
I use a British keyboard layout, not US, it's strange that this works fine for me but not you. How is your layout configured?

In my env:
`LANG=en_GB.UTF-8`

and in my sway config:
```
input "1:1:AT_Translated_Set_2_keyboard" {
  xkb_layout gb
}
```

**Comment by eXeC64** [comment]
I've had a playabout and this is the result of the approach imv currently takes for handling key bindings. It needs a bit of a refactor, and a slight change to how things are configured. That is, no more `Shift+X`, but rather `x` and `X` being different keys, and `:` being the same whether you have to press `Shift+;` or `m` for it.

I'm going to have a play with this this weekend to see if I can get some sensible behaviour.

**Comment by eXeC64** [comment]
This doesn't seem possible to resolve while continuing to use SDL. I've encountered enough bugs that I'm going to port imv to [glfw](https://www.glfw.org/). It's a pretty major change, and may cause tweaks to imv's bind system, as I'll be using [libxkbcommon](https://xkbcommon.org) to ensure proper handling of all keyboard layouts.

As a result, v3.1.0 is going to ship without this issue being resolved, but I'm going to have a v4 branch soon that'll respect your keyboard layout, but be less stable in the short term.

**Comment by eXeC64** [comment]
The master branch now contains logic to automatically detect the current keyboard layout and configuration (according to xkb) and respect it, on both X11 and Wayland.

Since master is now the working branch for v4, it's worth noting that binds are not fully backwards compatible. This is because the old way of handling keyboard input in imv was dumb, and couldn't be maintained while fixing layout issues.

**Comment by Eluminae** [comment]
Okay. Totally my bad.
I still got the inversing configurations but the package has been updated...

It works !
