### ISSUE TITLE
Colors in SVGs inverted?

### ISSUE THREAD

**Issue by HalosGhost** [eXeC64/imv#157]
## System

Distro: Archlinux
package: -git built from master

## Additional Information

librsvg version installed: librsvg 2:2.44.14+1+g17bb3cd6-1

## Problem

Okay, so this seems to be a really weird one…

Now that #149 is fixed (:tada:), I have been able to start using `imv` as my SVG viewer. 

For example, I can view the following image:

![the archlinux logo](https://www.archlinux.org/static/logos/archlinux-logo-dark-scalable.518881f04ca9.svg)

I see the same image with colors (note: seemingly not grayscale) inverted:

![inverted archlinux logo](https://0x0.st/zBim.png)

## Steps to reproduce

1. build `imv` from-source
2. navigate to a directory that contains an SVG which includes colors (e.g., `first.svg`)
3. run `imv` on the SVG file (e.g., `imv first.svg`)

Any ideas on what might be causing this or what other information might be helpful to narrow this down?

**Comment by eXeC64** [comment]
I'm not at my computer so I can't check now, but my guess would be a mismatch between the buffer format and what imv expects: RGB Vs BGR, for example.

**Comment by HalosGhost** [comment]
Some further information. I can now confirm that this does not happen with all images. I will start trying to put together a minimal example SVG to demonstrate the issue.

**Comment by HalosGhost** [comment]
Okay. I believe I a have a solid minimal failing case. And I believe you are entirely correct @eXeC64. Green does not appear to be affected. In fact, it specifically appears to be RGB/BGR.

Below is an SVG file which, when rendered correctly, should show two dots (from left-to-right): dark blue, and yellowish.

When shown in `imv`, I instead see (again, from left-to-right): dark green-yellow, and light teal.

This seems to confirm that the Red bytes and Blue bytes are being swapped:

```svg
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Created with Inkscape (http://www.inkscape.org/) -->

<svg
   xmlns:svg="http://www.w3.org/2000/svg"
   xmlns="http://www.w3.org/2000/svg"
   xmlns:xlink="http://www.w3.org/1999/xlink"
   version="1.0"
   width="100"
   height="100">
   <circle r="15" style="fill:#999900" cx="75" cy="50" />
   <circle r="15" style="fill:#005555" cx="25" cy="50" />
</svg>
```

**Comment by eXeC64** [comment]
I'll get this fixed in the next few days

**Comment by HalosGhost** [comment]
@eXeC64, I want to make sure you know that you are awesome and you do great work. Thank you for your dedication and let me know if I can help!

**Comment by eXeC64** [comment]
I'm seeing the same behaviour on my system. I could've sworn this was working properly before. According to documentation the gdkpixbuf librsvg provides always has colours in the same order. Anyway, I downloaded a bunch of sample svgs from w3, and without the fix the colours are definitely wrong. With a small tweak, they're all correct.

Ah well, applying the fix.
