### ISSUE TITLE
SVGs do not scale cleanly

### ISSUE THREAD

**Issue by HalosGhost** [eXeC64/imv#158]
## System

Distro: Archlinux
package: -git built from master

## Additional Information

librsvg version installed: librsvg 2:2.44.14+1+g17bb3cd6-1

## Problem

Unlike raster graphics which can only be scaled approximately (losing definition in the process), SVGs (and all vector graphics) are designed such that they can be scaled infinitely without any loss of definition. Of course, this means that, on most monitors attached to computers, the vector must be rendered to a raster before it can be displayed. Normally, this render would happen just before displaying the vector (as this will preserve the definition as well as possible).

However, when viewing an SVG in `imv`, it appears as though the render-to-raster happens before scaling the image to the view. The result is that, if an SVG were defined in terms of small units, `imv` displays it either without scaling or scaled to the view (as it does with any image). When scaled to the view, the SVG is as blurry as if it had been a raster all along rather than an SVG.

## Steps to reproduce

1. build `imv` from-source
2. navigate to a directory that contains an SVG which is defined in terms of a small width and height
3. run `imv -s full` on the SVG file
4. Notice that, rather than seeing the image scaled to the view in perfect definition, the image will be displayed blurry.

Is this a very difficult issue to fix?

**Comment by eXeC64** [comment]
At present, the interface of the image loaders emits bitmaps only. Obviously the loader has no idea of the display resolution (not should it). The fix here would be for the intermediate format to be something more abstract that can be given a buffer and target resolution to fill.

It's quite a refactor though, so I wouldn't hold your breath. I want to focus on small issues and polishing before the next release.

**Comment by eXeC64** [comment]
The next release is turning into quite a refactor. Since I'm using cairo for non-bitmap rendering (text, backgrounds, etc.) a lot of the groundwork for this is done. I'm going to try and have it as part of v4

**Comment by eXeC64** [comment]
I have this working in my v4 branch. There's still some cleanup to do, but consider it done.

**Comment by eXeC64** [comment]
On the left is imv v4, on right v3.1
![image](https://user-images.githubusercontent.com/808760/59962686-b3b3c900-94e0-11e9-91aa-0051cb9ec9c0.png)

**Comment by HalosGhost** [comment]
Absolutely outstanding! :tada:

**Comment by eXeC64** [comment]
This is now merged to master, and will be part of the v4 release.

**Comment by HalosGhost** [comment]
:D
