### ISSUE TITLE
Fix outstanding memory leaks

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#165]

**Comment by rien333** [comment]
Could be that I'm using ipc wrong, but issuing a command over the ipc socket like `printf "bg 000000" |  socat - UNIX-CONNECT:"/run/user/1000/imv-9253.sock"` (please tell me if so! same happens for `nc`) makes `imv` spiral toward using almost all CPU of my i7. Eventually, I think this also leaks memory. At least, the august 8 version of `imv` leaked memory during ipc, iirc.

**Comment by eXeC64** [comment]
It was indeed a bug in how I was handling the socket. It's now fixed by c7cbdf0.
The failure to cleanup the socket was a result of this, and should no longer happen.

**Comment by eXeC64** [comment]
I did some digging with valgrind and found a few minor leaks. I've fixed them up, everything else I could see seem to be leaks in external libraries outside my control. Marking this fixed.
