### ISSUE TITLE
imv leaves behind unused ipc sockets

### ISSUE THREAD

**Issue by rien333** [eXeC64/imv#166]
I've been playing around with the ipc functionality. Pretty neat, but I've noticed that every new `imv` instances creates a new socket. I've seen programs doing this differently - e.g. basing it's name on a md5 of the username - but I suppose the current approach makes sense because you can have multiple `imv` sessions open. However, `imv` doesn't clean up the ipc after it exits. This might have been intentional, as I don't know a lot about ipc, but if not, the current approach is a bit messy/might complicate scripts.

**Comment by eXeC64** [comment]
I can no longer reproduce this after c7cbdf0. Marking fixed.
