### ISSUE TITLE
PNG grayscale 16-bit images can't be opened

### ISSUE THREAD

**Issue by igsha** [eXeC64/imv#167]
Generated image by `imagemagick` can't be opened by `imv`:
```
$ convert rose: -resize 700 -depth 16 -colorspace Gray out.png
$ file out.png
out.png: PNG image data, 700 x 460, 16-bit grayscale, non-interlaced
```
I can open this image by `ffplay` or `viewnior`. But `imv` shows only blank screen.

Generated image example:
![out](https://user-images.githubusercontent.com/5345170/63014421-2b75f280-be97-11e9-8293-9822be5589ea.png)

**Comment by eXeC64** [comment]
Thanks for the bug report, this is now fixed in master by ff2e28f and d371c7a.
