### ISSUE TITLE
Option to quit when reaching end/start

### ISSUE THREAD

**Issue by q3cpma** [eXeC64/imv#168]
Hello,

I wonder if it'd be possible to add an option to quit when trying to go forward/back while being at the  end/start with a specific error code or message for each case. The goal would be to replace the dirty hack of using a patched sxiv in https://repo.or.cz/sxiv-manga-reader.git
If you're okay with it, I can make a patch for it.

**Comment by eXeC64** [comment]
The `-x` flag already quits when trying to go past either end, though there's no special exit code for this, since it's considered a successful/clean exit.

**Comment by eXeC64** [comment]
I had a think about what would solve your use case, and in c7e391d I added a new environment variable for imv to export when running external commands: `$imv_pid`. With this and `imv-msg` it should be easy to write a shell script that'll check if imv has reached the end of its input, and either change to the next image or trigger some custom behaviour. That behaviour could either be quitting imv, or closing all open images and opening a new set instead.

Does that satisfy your use case with an unpatched imv build?

**Comment by q3cpma** [comment]
if I understand well, this would involve using imv-msg to send messages to yourself, but with a script in between? Should be possible, even if quite strange compared to how I currently do it.

**Comment by q3cpma** [comment]
After looking a bit, the only think I seem to lack is a way to close all the pictures. It's a very elegant way to solve the problem; almost Plan 9 tier.

**Comment by eXeC64** [comment]
For that, I can extend the `close` command to take an optional argument: either the index to close, or `all` to close all open images.

**Comment by eXeC64** [comment]
Optional argument to `close` added in c6ce270. I think this issue is resolved.
