### ISSUE TITLE
imv.sh should use a different path for sh

### ISSUE THREAD

**Issue by DarkDefender** [eXeC64/imv#171]
At least on Gentoo bash and sh is located in `/bin/` and not `/usr/bin`.
I'm guessing this will be an issue for other distros as well

**Comment by eXeC64** [comment]
Ah, I just went by what `which sh` on my system told me. There's a symlink in `/usr/bin` as well, so I'm happy to fix it. Fixed in 96b6dc3.

**Comment by DarkDefender** [comment]
Thanks!
