### ISSUE TITLE
Bundled imv_config need updating

### ISSUE THREAD

**Issue by DarkDefender** [eXeC64/imv#172]
The current imv_config is outdated and will not work correctly anymore.

After installing imv on the system it will break navigation and other shortcuts.

**Comment by eXeC64** [comment]
Thanks for reporting this. I'll get it sorted.

**Comment by eXeC64** [comment]
Fixed by cf70629

**Comment by DarkDefender** [comment]
Don't know if this is related, but `scaling_mode next` doesn't seem to work. Did this config option also change?

**Comment by eXeC64** [comment]
Oops, got that in 9850d9c
