### ISSUE TITLE
[Sway] imv stops taking keyboard input when moved to an other workspace

### ISSUE THREAD

**Issue by DarkDefender** [eXeC64/imv#174]
This started happening after some of the recent changes to imv.

If I open up imv all keyboard shortcuts works. But if I move imv to an other workspace, it stop accepting keyboard input.

**Comment by eXeC64** [comment]
Turns out I wasn't doing a good job of handling keyboard input, but this is now fixed by 9e1d6e2 and 7418911.

Thanks for catching this one, it would've been embarrassing to go out in v4.
