### ISSUE TITLE
Segmentation fault running imv on wayland

### ISSUE THREAD

**Issue by Fixallmyproblems** [eXeC64/imv#180]
I compiled both the stable latest releases of SDL2 and imv as well as the git master branches of both SDL2 and imv and I get an error code of 
```
Segmentation fault
```

every time, I'm on wayland running velox -> https://github.com/michaelforney/velox and I have no clue why it throws a Segmentation fault at me when imv-x11 works fine under Xwayland, I'd like to not rely on Xwayland for too much stuff and imv was the only suckless listed software that rocks with native Wayland support so I'd like to get this Segmentation fault problem solved.

**Comment by eXeC64** [comment]
SDL2 is no longer used by imv, Wayland is used directly now, so it's not going to be that.

Anyway, I installed velox and was able to reproduce your segfault. It is now fixed in the master branch by e3cf680.
