### ISSUE TITLE
[Sway/wayland] imv loses its titlebar/outline when set to floating

### ISSUE THREAD

**Issue by DarkDefender** [eXeC64/imv#182]
When I toggle the imv window (wayland backend) to be floating, it loses the outline and titlebar. This persists even after making it non floating again.

**Comment by eXeC64** [comment]
Generally in Wayland, applications are supposed to draw their own decorations (titlebar etc.), however there's an extension that allows clients to negotiate for the compositor to draw them on its behalf. imv doesn't yet implement this, so it's kind of weird that a decoration gets shown at all outside of the tabbed and stacked layouts in sway.

I'm going to close this, as I believe this is a bug in sway. It could be a future enchancement to imv to implement this extension, and have an option for enabling/disabling compositor decorations but I'd rather leave that option as a sway app_id based per-application configuration.
