### ISSUE TITLE
Document default binds in man page

### ISSUE THREAD

**Issue by gregf** [eXeC64/imv#188]
If I run imv *.jpg how do I switch between the images. The manpage seemed to point to n and p, but they are doing nothing on my archlinux system.

**Comment by eXeC64** [comment]
By default the arrow keys will switch image, as they are bound to the `next` and `prev` commands. You can hit `:` to enter command entry mode. Though you do raise a good point: the default binds aren't documented anywhere in the man page any more.This should be fixed to make imv easier to pick up

**Comment by eXeC64** [comment]
Does typing `:next` change image? If you hit `d` it should toggle the text overlay on, which will show how many images open you have. Does it show more than one image open?

if you type `:bind n next`, does that make the 'n' key go to the next image?

**Comment by eXeC64** [comment]
That's very strange. `:bind <Left> prev` and `:bind <Right> next` are in the defaults, so the arrow keys should work. `<Up>` and `<Down>` working for zoom rules out all the possible causes I can think of

**Comment by eXeC64** [comment]
Are you putting that in the `[binds]` section of your config?
You can do the following to have stdout show you when a bind was triggered

    n = next; exec echo "next"
    p = prev; exec echo "prev"

**Comment by eXeC64** [comment]
Binds are documented now, so closing
