### ISSUE TITLE
curl 'Example Usage' doesn't work. Possibly imv ignoring stdin

### ISSUE THREAD

**Issue by rehaby** [eXeC64/imv#189]
Using ubuntu 18.04 with imv 4.0.0 and curl 7.58.0 the example commands in the readme result in a blank imv window. 

# Viewing images from stdin
curl http://somesi.te/img.png | imv -

Reading up on curl -s should make curl silent and '-o -' should force curl to output binary data to standard out. So I think the command below should work

curl -so - https://i.redd.it/5fmqo3b0i1j31.png | imv -

but imv seems to ignore standard input

**Comment by eXeC64** [comment]
Indeed you're right. Looks like a regression.

**Comment by DarkDefender** [comment]
The issue is here: https://github.com/eXeC64/imv/blob/master/src/navigator.c#L77

Previously it didn't exit if it couldn't resolve the path. For stdin data, there is no valid path on the disk so this check should always fail.

**Comment by rehaby** [comment]
I've created a pull request with the fix. Not really sure how to work github so hopefully I've done it correctly

**Comment by eXeC64** [comment]
Fixed by #199

**Comment by filalex77** [comment]
Would be nice to get a new release.
