### ISSUE TITLE
WebP support

### ISSUE THREAD

**Issue by NOTtheMessiah** [eXeC64/imv#190]
[WebP](https://en.wikipedia.org/wiki/WebP) is an increasingly common file format from Google for both lossy and lossless compression now that Firefox has implemented rendering it. However, Linux seems to lack an image viewer that supports it, despite seemingly [being supported by FreeImage](http://freeimage.sourceforge.net/features.html).

**Comment by eXeC64** [comment]
Ah, imv's primary backend is FreeImage, so webp is already supported :champagne: . I just tested v4.0.1 against a couple of images from [here](https://developers.google.com/speed/webp/gallery1) which worked fine.

Is it not working for you?

**Comment by mb720** [comment]
Some WebP images can be animations, like GIFs. I haven't found a way to play those images with imv. I use Firefox as a fallback.
