### ISSUE TITLE
Keystrokes all uppercase after moving image to another monitor

### ISSUE THREAD

**Issue by mb720** [eXeC64/imv#192]
Hi and thanks for imv!

I'm using i3 4.17 on my Arch Linux laptop with an external monitor.

When I open up an image with imv on the laptop's monitor everything works fine. But when I move that image to the external monitor something weird happens:

All keys I press within imv are now uppercase. For example, typing ":overlay" appears as ":OVERLAY".

This is problematic since I now can't properly close the image anymore: "q" comes out as "Q".

Thinking that all my applications are affected by this bug, I moved a Bash and a Zathura instance from the laptop's monitor to the external monitor. But they keep working normally.

The bug also occurs the other way around: If I'm on the external monitor and open an image with imv, everything works fine. As soon as I move that image to a workspace on the laptop, letters are all uppercase.

My imv version is v4.0.0-rc1.

Thanks!

**Comment by eXeC64** [comment]
This bug was caught and fixed in a later rc. I think arch has the latest version now (v4.0.1) which should work fine.

**Comment by mb720** [comment]
You're right. After upgrading to 4.0.1 the bug is gone.

Thanks!
