### ISSUE TITLE
Backends and Freeimage question

### ISSUE THREAD

**Issue by q3cpma** [eXeC64/imv#195]
Hello,

are you planning to progressively replace Freeimage or complement it? Why don't you use Freeimage exclusively (or another do-it-all library like Imagemagick/graphicsmagick, which is probably more ubiquitous)?

My primary reason for asking this is that Freeimage seem to encourage bundling and isn't updated very often.

**Comment by eXeC64** [comment]
FreeImage was originally chosen since it provided support for animated gifs, but the recent addition of libnsgif as a backend for animated gifs does allow for other libraries to be used, but they may not support PSD, webp, or other less common formats. I've currently no plans to replace FreeImage, but if downstream users want imv but not FreeImage they should be free to compile it with different backends enabled and still have support for most formats.

> FreeImage seem to encourage bundling

What do you mean by that?

> isn't updated very often

That's not necessarily a bad thing. If it works and there aren't any known vulnerabilities in the wild, there's not much call to change things.

**Comment by q3cpma** [comment]
On Sun, Sep 08, 2019 at 12:16:19PM -0700, Harry Jeffery wrote:
> FreeImage was originally chosen since it provided support for animated gifs, but the recent addition of libnsgif as a backend for animated gifs does allow for other libraries to be used, but they may not support PSD, webp, or other less common formats. I've currently no plans to replace FreeImage, but if downstream users want imv but not FreeImage they should be free to compile it with different backends enabled and still have support for most formats.
>
> > FreeImage seem to encourage bundling
>
> What do you mean by that?
For example, looking at https://www.archlinux.org/packages/community/x86_64/freeimage/, they use Freeimage's internal libpng (well, it's arguably Arch's fault) which, coupled with Freeimage's slow release cycle, could have some security consequences in case of libpng vuln.
On Gentoo, we use the system libpng, but for example, netpbm is bundled on both distros.

>
> > isn't updated very often
>
> That's not necessarily a bad thing. If it works and there aren't any known vulnerabilities in the wild, there's not much call to change things.
Well, it's only a problem with bundled libs, indeed.


Bundling (copy pasting libs in your tree) in general isn't considered a good idea for many reasons.

**Comment by q3cpma** [comment]
In fact, looking both at the pkgbuild and the ebuild, unbundling needs some really dirty patching and isn't really supported by upstream.
Maybe I'll help writing some backends for important formats (can't use GPL libs, though, right?).

**Comment by q3cpma** [comment]
After looking at both the pkgbuild and ebuild, unbundling is done through very dirty patching and is obviously not supported by upstream.
I might help writing some backends for stuff like webp and netpbm to solve this. Can imv link with GPL libs?

**Comment by q3cpma** [comment]
Whoops, sorry for the double post.

**Comment by eXeC64** [comment]
Deleted the double-post.

To reiterate, I don't presently have plans to switch from FreeImage as the default backend for imv, but if you're uncomfortable with it, I'd be happy to maintain support for other libraries such as imlib2 as alternatives to FreeImage, or more specific libraries can be added directly such as libspng.
