### ISSUE TITLE
Relicense to GPL

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#20]
FreeImage being licensed under the GPL makes the legal state of imv a bit complex. For our sanity let's just switch from MIT to GPL and avoid the mess.

I'll need consent from all contributors thus far, which is myself, @jdiez, and @guiniol.

Please post a comment confirming your approval. Failure to do so will result in your contributions having to be removed.

**Comment by guiniol** [comment]
Fine by me

**Comment by jdiez17** [comment]
:thumbsup:

**Comment by eXeC64** [comment]
Done.
