### ISSUE TITLE
Overlay appearance customization

### ISSUE THREAD

**Issue by rien333** [eXeC64/imv#203]
A somewhat easy one: it would be great if you could decide on the color of the overlay (including it's transparency, bc I think it's transparent already?), and maybe also if you want it at the top or bottom. Obviously, you will need to be able to set the overlay text color as well. 

Might be able to do this one myself, if I ever find the time.

**Comment by st4ll1** [comment]
I have a draft of this feature implemented
https://github.com/eXeC64/imv/compare/master...st4ll1:overlay_color

Its working, but i am not happy with it yet

**Comment by lokesh-krishna** [comment]
Isn't this already a thing now?

**Comment by rien333** [comment]
Yes, you're right.
