### ISSUE TITLE
[FR] :write like in vim

### ISSUE THREAD

**Issue by ReekyMarko** [eXeC64/imv#206]
I would love to have a command to write the current image to a file, like in vim. For example:
```
:write ~/filename.jpg
:w ~/Downloads/filename.png
```

**Comment by eXeC64** [comment]
Writing files is very different from the loading that imv currently does. This isn't going to be added, but you can get this functionality having an alias invoke imagemagick's `convert` tool:

```
[aliases]
write = exec convert "$imv_current_file"
```

`:write out.jpg` will run `convert "$imv_current_file" out.jpg`

**Comment by ReekyMarko** [comment]
Alright thanks :pray:
