### ISSUE TITLE
Start at specified picture

### ISSUE THREAD

**Issue by autrimpo** [eXeC64/imv#21]
A way to specifiy a picture to start at when launched (similar to sxiv's "-n" or feh's "-|") would be great.
Originally I wanted to just submit a pull request, however after starting to work I noticed your way of parsing arguments can't handle a value after an option. Should I rewrite it using *getopt* and submit a PR for that as well? Or do you want to solve it another way?

**Comment by eXeC64** [comment]
The current options parsing is very rudimentary, long term I would like to move to getopt or similar. If you could replace the current parsing with getopt, that'd definitely be appreciated. I'd like to keep that as a separate pull request to this issue though, so if you do want to do that, could you submit it as a new pull request?

**Comment by autrimpo** [comment]
I could, and of course as a separate PR, that's what I intended. I should've probably phrased that a bit better.
