### ISSUE TITLE
Makefile: the doc target should be called by the imv target

### ISSUE THREAD

**Issue by paride** [eXeC64/imv#213]
In the Debian packaging I'm leaving out the `install` target and install the files "manually" (using the packaging helper scripts). The default Makefile target is `imv`, which leaves out the `doc` target, the one that builds the manpages. This target is called when calling the `install` target.

It is of course very easy to add a `make doc` where necessary, however I think that building the manpages belongs more to the main `imv` target than to the `install` target.

**Comment by escondida** [comment]
This really seems more like the exact use case for having an "all" target (which would, like clean, of course be marked .PHONY), which could then be the default and depend on "imv" and "doc" (and anything else that becomes necessary later).

**Comment by eXeC64** [comment]
The make all target already does exactly that. I don't think there's any changes required. Closing. Feel free to re-open if I've missed something.
