### ISSUE TITLE
.desktop file lacks a Keywords entry

### ISSUE THREAD

**Issue by paride** [eXeC64/imv#214]
The .desktop file does either not contain a "Keywords" entry or it does not contain any keywords not already present in the "Name" or "GenericName" entries.

Refer to https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html, https://bugs.debian.org/693918, and https://wiki.gnome.org/Initiatives/GnomeGoals/DesktopFileKeywords for details.

**Comment by eXeC64** [comment]
Adding a keywords entry. Thanks.
