### ISSUE TITLE
cumbersome desktop file shows up Xorg menus.

### ISSUE THREAD

**Issue by CaptainBloodz** [eXeC64/imv#218]
Maybe desktop entry NoDisplay=true is relevant.

**Comment by CaptainBloodz** [comment]
homebrewed gentoo's user patch
--- imv-2.1.3/files/imv.desktop.old	2016-10-22 14:35:20.000000000 +0300
+++ imv-2.1.3/files/imv.desktop	2019-12-16 11:49:53.355124443 +0300
@@ -4,6 +4,7 @@
 GenericName[en_US]=Image viewer
 Comment=Fast freeimage-based Image Viewer
 Exec=imv %F
+NoDisplay=true
 Terminal=false
 Type=Application
 Categories=Graphics;2DGraphics;Viewer;

**Comment by eXeC64** [comment]
Thanks for the suggestion.I'll add `NoDisplay` to the desktop file.
