### ISSUE TITLE
Add webm support

### ISSUE THREAD

**Issue by giodamelio** [eXeC64/imv#22]
With webm getting more and more common, it would be awesome to support it. It might be a bit close to video for an image viewer, but since people often use webm like gifs(see [Gfycat](gfycat.com) and [Imgur's gifv](https://imgur.com/blog/2014/10/09/introducing-gifv/)), it seems like it might fit.

**Comment by eXeC64** [comment]
For video files like webm, mpv is a much more suitable player/tool.

gif support is as close to video as I'd like imv to get.
