### ISSUE TITLE
Open an image with its siblings (with an argument or a config option)

### ISSUE THREAD

**Issue by guildem** [eXeC64/imv#223]
This software is a great tool, but for my use case has one limitation.

If i'm in a folder with multiple image files, I find the first one I want to see and I instinctively start with `imv first.jpg`. But unfortunately if I go right, no other image is shown.

I know I can start it with `imv . -n first.jpg` to start the folder and go to the right file directly, but if I have a long path a command like `imv my/ultra/long/path/with/images -n my/ultra/long/path/with/images/first.jpg` is not pretty.

A solution is to have a function in our shell finding the absolute path of the file and creating the right command, but why grow up config files if a few lines into the software are enough, right ?

Maybe there can be an option to load a file with its siblings (if allowed, only if one file given, not with stdin obviously) with an argument like `imv -a first.jpg` (a for ALL the siblings...) and an option to always enable this behavior it in config file (false by default).

What do you think about this functionality ? Would it be interesting to have it ?

**Comment by EnfrigFalco** [comment]
This would be super awesome. Spent the last 30 min thinking I had an issue with my Sway/Wayland. I cannot think of an image viewer were this is not the case. You open an image from a file manager and the arrow keys provide by default navigation of 'prev' or 'next' image. This should be default IMO.

**Comment by somini** [comment]
This can be solved with a shell script and a desktop file.

Add this on your `$PATH` (`~/bin/imv-folder`) and `chmod +x` it:
```
#!/bin/sh
image="$1"
exec imv "$(dirname "$image")" -n "$image"
```

Add a desktop file to call it (`~/.local/share/applications/imv-folder.desktop`:
```
[Desktop Entry]
Name=imv-folder
GenericName=Image viewer
GenericName[en_US]=Image viewer
Comment=Fast freeimage-based Image Viewer | Open all images on a folder
Exec=imv-folder %f
NoDisplay=true
Terminal=false
Type=Application
Categories=Graphics;2DGraphics;Viewer;
MimeType=image/bmp;image/gif;image/jpeg;image/jpg;image/pjpeg;image/png;image/tiff;image/x-bmp;image/x-pcx;image/x-png;image/x-portable-anymap;image/x-portable-bitmap;image/x-portable-graymap;image/x-portable-pixmap;image/x-tga;image/x-xbitmap;
Name[en_US]=imv
Icon=multimedia-photo-viewer
Keywords=photo;picture;
```
Note the `%f`, this is for a single file. This means opening several files will use the regular `imv.desktop`.

Then you should have a `imv-folder` program you can associate as default program for opening images.

---

If anyone else confirm this is working I can open a PR.

**Comment by guildem** [comment]
> This can be solved with a shell script and a desktop file.
And you're right, that's what I decided to use for now. But make it default (or configurable to be the default) directly into the software could be better IMO.

> If anyone else confirm this is working I can open a PR to include this on the package itself.
This is the same script I use (so it is working), and the Desktop file test seems to work on my setup.

**Comment by somini** [comment]
Updated  MR #225 to the new meson build system.
