### ISSUE TITLE
libnsgif - which version is used with 'imv'?

### ISSUE THREAD

**Issue by colemickens** [eXeC64/imv#227]
I package `imv` at HEAD for `nixpkgs-wayland` and was going to help update the `nixpkgs` package as well, for the switch over to meson. In the process, I noticed that we were not building with GIF support.

I'd like to potentially address that. I'm curious, is `imv` usually built against the official netsurf library? Given it's dependence on netsurf's build system, I was hoping for something similar and I did see there's a more standalone fork here - https://github.com/jcupitt/libnsgif but I'd prefer not to deviate from standard packaging practices for `imv`.

Any suggestions?

**Comment by eXeC64** [comment]
Sorry for the (very) late response. I don't target a particular version of libsngif, just whatever happens to be in my distro's repository.
