### ISSUE TITLE
Directory navigation commands

### ISSUE THREAD

**Issue by alebastr** [eXeC64/imv#231]
One of the features I really miss from `feh` - prev_dir and next_dir commands.
Quote from `feh(1)`:

> `[, ] [prev_dir, next_dir]`
> Jump to the first image of the previous or next sequence of images sharing a directory name in the current filelist. Use `--sort dirname` if you would like to ensure that all images in a directory are grouped together.

**Comment by eXeC64** [comment]
This should be handled now by the `imv-folder` script in the contrib directory.

**Comment by alebastr** [comment]
imv-folder does not provide shortcuts for jumping to the next/prev directory though

**Comment by eXeC64** [comment]
Ah apologies, I misunderstood. I thought you meant next/priv image within a directory.

Once again that's not something I plan to support natively, so I can only suggest expanding the imv-folder script.
