### ISSUE TITLE
if duplicated please letme know. libnsgif.h not found, but

### ISSUE THREAD

**Issue by mh4nx7net** [eXeC64/imv#237]
i've install of those dependency that we need to be installed
here down below
![grimshoot-slurp-2020-03-26-10-33-59](https://user-images.githubusercontent.com/33443311/77607560-56f0ad80-6f4d-11ea-8330-832c01be072e.png)
but, then
![grimshoot-slurp-2020-03-26-10-33-10](https://user-images.githubusercontent.com/33443311/77607532-36c0ee80-6f4d-11ea-9feb-48a486a0305d.png)

what iam just missing ?

**Comment by mh4nx7net** [comment]
![grimshoot-slurp-2020-03-26-10-43-28](https://user-images.githubusercontent.com/33443311/77608032-a5527c00-6f4e-11ea-8a82-2b90b9eaa508.png)
ok, just done by changing " instead of <>

**Comment by eXeC64** [comment]
Sounds like this is resolved.
