### ISSUE TITLE
weird mouse zooming behaviour

### ISSUE THREAD

**Issue by nycex** [eXeC64/imv#239]
When scrolling into the image, the zooming gets slower the more zoomed in you are and it gets faster the more zoomed out you are. This behaviour is kind of weird, it would feel more natural to me if the zoom factor would be constant.

**Comment by Pascal-So** [comment]
Can confirm the issue. It looks to me as if the zooming happens on a linear scale as opposed to exponentially.

**Comment by eXeC64** [comment]
Should be fixed now
