### ISSUE TITLE
Divide by Zero due to max_texture_height

### ISSUE THREAD

**Issue by jecxjo** [eXeC64/imv#24]
Running on 64bit Gentoo, i3 WM 4.10.4, Xorg server 1.16.4, SDL2 2.0.3-r200, Freeimage 3.15.4.

When I try loading any type of image (jpg, png) the code crashes with a `Floating point exception`. Looking through the code the crash occurs at `imv_texture_set_image` in `texture.c` line 62.

    45| int imv_texture_set_image(struct imv_texture *tex, FIBITMAP *image)
    46| {
    47|   FIBITMAP *frame = FreeImage_ConvertTo32Bits(image);
    48|   tex->width = FreeImage_GetWidth(frame);
    49|   tex->height = FreeImage_GetHeight(frame);
    50|
    51|   char* pixels = (char*)FreeImage_GetBits(frame);
    52|
    53|   /* figure out how many chunks are needed, and create them */
    54|   if(tex->num_chunks > 0) {
    55|     for(int i = 0; i < tex->num_chunks; ++i) {
    56|       SDL_DestroyTexture(tex->chunks[i]);
    57|     }
    58|     free(tex->chunks);
    59|   }
    60|
    61|   tex->num_chunks_wide = 1 + tex->width / tex->chunk_width;
    62+>  tex->num_chunks_tall = 1 + tex->height / tex->chunk_height;

`void imv_init_texture` calls `SDL_GetRendererInfo` which in my case returns a `SDL_RendererInfo.max_texture_height` that equals zero. This value is then used in the calculating of chunks which causes the divide by zero.

    20| void imv_init_texture(struct imv_texture *tex, SDL_Renderer *r)
    21| {
    22|   tex->renderer = r;
    23|   tex->num_chunks = 0;
    24|   tex->chunks = NULL;
    25|
    26|   SDL_RendererInfo ri;
    27|   SDL_GetRendererInfo(r, &ri);
    28|   tex->chunk_width = ri.max_texture_width;
    29+>  tex->chunk_height = ri.max_texture_height;
    30| }

**Comment by jdiez17** [comment]
Thanks for the in-depth analysis. I'm not sure why `max_texture_height` would be 0, but I've seen at least 2 other people with the same problem.

**Comment by eXeC64** [comment]
I was able to reproduce this by setting SDL to use its software renderer. When that happens the maximum texture dimensions are reported to be 0 (presumably indicating unlimited size). I've just pushed a change that'll set the maximum chunk sizes to 4096x4096 when that happens.

Hopefully that fixes the issue. Could you verify this please?
