### ISSUE TITLE
image overview

### ISSUE THREAD

**Issue by nycex** [eXeC64/imv#243]
when opening multiple files with imv, it would be great if you could open a view where you can see them all (maybe not all, set a limit for rows and columns and then scroll or something like that), like you can in sxiv

**Comment by max-k** [comment]
I agree with you. A "thumbpane" could be a very nice addition to ease browsing in large pictures folder.

Here is an example of a pane provided by mirage, a gtk/x11 based image viewer.

![image](http://mirageiv.sourceforge.net/images/ss2.png)

**Comment by eXeC64** [comment]
Duplicate of #38
