### ISSUE TITLE
how to get current selected filename

### ISSUE THREAD

**Issue by eoli3n** [eXeC64/imv#246]
in man i can read
```
ENVIRONMENT VARIABLES
       When imv executes a shell command, it provides a number of environment
       variables, exposing imv’s state. These environment variables are also
       available when customising the window’s title, or the overlay text.

      $imv_current_file
           Path of currently selected image.
```

```
/usr/share/icons 47s
➜ imv -d **/*back* &

/usr/share/icons 7s
➜ echo $imv_current_file

```

**Comment by eXeC64** [comment]
Unix processes can only expose environment variables to their children, not their parents, like the shell that ran imv. Any command run from imv will have access to these variables, for instance `:exec echo $imv_current_file` prints the current filename to stdout.

You may wish to create a bind to run a command against the current file. You can also look at using `imv-msg` to send such a command to imv, if you want it controlled by an external script.

**Comment by eoli3n** [comment]
thanks
