### ISSUE TITLE
How can I copy an image I'm seeing to to the clipboard?

### ISSUE THREAD

**Issue by gdiazlo** [eXeC64/imv#250]
I use grim and slurp to capture the screen and send it to imv. Then if I like the image, I want to copy it to the clipboard. Is there a way to create a copy binding? 

thanks!

**Comment by cshapeshifter** [comment]
I'm guessing you're best off scripting it such that grim captures to a temporary file, open that in imv and then you can just bind a key to call wl-copy from wl-clipboard to load the temporary file into the clipboard.

**Comment by gdiazlo** [comment]
That's what I am doing now, but that  copies the size of the screen and not the image itself :(

**Comment by cshapeshifter** [comment]
Maybe imv simply needs to be able to output the image data to stdout for easy piping to wl-copy an the like. Actually I think this would be a simple and versatile feature, should be easy enough to implement.

**Comment by rifazn** [comment]
You can use imv's `exec` command to copy the current file being viewed to your clipboard.

With your image opened in imv, type

```
:exec wl-copy < "$imv_current_file"
```

And this will copy the image to your clipboard (assuming `wl-copy` is your clipboard manager), ready to be pasted anywhere!

You can also add a keybinding to imv's config under the `[binds]` section to copy current image to clipboard at will, like so

```
[binds]
y = exec wl-copy < "$imv_current_file"
```

So, in your case, if you like the screenshot, just pressing `y` will copy the image to your clipboard.

**Comment by eXeC64** [comment]
I would recommend the solution rifazn suggested. I don't have any plans to integrate imv with the clipboard directly.
