### ISSUE TITLE
Add config.h config.def.h capabilities

### ISSUE THREAD

**Issue by ghost** [eXeC64/imv#251]
I recently discovered the method of copying config.def.h to config.h and editing the latter for making keybindings and other settings in the language the application was programmed in. I really enjoy this method, and I really enjoy this image viewer, so I would love if they could be combined.

I am not suggesting completely discarding the config file. I propose that a config.def.h be added to the project along with a way to turn off scanning the config file for settings (to make the application run faster).

I don't know what the best method for turning off the config file is, but I suppose it's one of these:

- Use the preprocessor (`#def scan_config`)
- Use a C variable (`bool scan_config`)
- Use a makefile instruction (`make noconfig install`)

I see that this application uses meson, which I don't know anything about. So for the last option (with the makefile) it would be whatever the meson equivalent is.

**Comment by eXeC64** [comment]
I'm glad you enjoy using imv, but I'm afraid I don't intend to support this configuration approach upstream. Hopefully I'm a lazy enough maintainer that managing a fork with your config.h isn't too onerous :)
