### ISSUE TITLE
imv: bad magic number

### ISSUE THREAD

**Issue by kanyck** [eXeC64/imv#252]
The window opens black when trying to open images. In the terminal:
`/home/kanyck/image.jpg: Not a TIFF or MDI file, bad magic number 55551 (0xd8ff)`
The same with .png file (yet different magic).
imv-4.1.0
enabled: freeimage, jpeg, png, svg, tiff, wayland

**Comment by kanyck** [comment]
UPD: it looks like freeimage communication issue. However, in spite of enabling openjpeg backend I cannot see it on `imv -h`. I've installed imv on another machine, it works fine there. On the laptop it fails, no matter whether it is X or wayland.

**Comment by Ypnose** [comment]
Same issue here with `4.2.0` in a Wayland only setup. Extremely infuriating.

**Comment by ryanerwin** [comment]
Probably old news, but recompiling with the commit indicated here did fix it for me. Works great!

Thank you!!!
