### ISSUE TITLE
.ora (openraster) and .kra (krita document) support

### ISSUE THREAD

**Issue by ledti** [eXeC64/imv#26]
With Krita becoming more popular, it might be worth adding support for these formats. They're both open specifications. Mypaint, another painting application, defaults to .ora

I've uploaded a tar archive with an example of each file. ([1](https://github.com/ledti/dotfiles/raw/3f209f6d06f74b871d56fac384877d973b6d0673/temp/ora_and_kra.tar))

Renaming either file with a .zip extension allows you to extract them.

Both formats contain a `mergedimage.png` in the root file directory after extraction, which is what imv would want to open.

I believe .kra was based on .ora. ([2](http://www.freedesktop.org/wiki/Specifications/OpenRaster/Draft/FileLayout/))

**Comment by eXeC64** [comment]
This is definitely something to consider for the future. There's a couple of image formats I'd like to add support for, but will require either extending FreeImage, or providing custom handling code.

When I get around to doing that, I'll be sure to try and include these (given their relative simplicity).

**Comment by eXeC64** [comment]
I do not have any plans to use multiple back-ends for loading images. I recommend lobbying FreeImage to add support for this format if you would like imv to support it.
