### ISSUE TITLE
Add contrib directory

### ISSUE THREAD

**Issue by knezi** [eXeC64/imv#261]
Thanks for this nice software, just a little note, it would be nice to have a contrib directory for some user scripts to share it with others.

One example is the following script. Of course, it needs a bit polishing, but it could be useful for someone (I use it to get previews in ranger).

```sh
#!/bin/sh

# "$1" will be opened

# start imv if not running
read pid </tmp/imv.pid

if ps -p $pid >&/dev/null; then
	:
else
	screen -d -m bash -c "imv -c 'exec echo \$imv_pid >/tmp/imv.pid'"
	sleep 0.5
	read pid </tmp/imv.pid
fi

path=`realpath "$1"`
imv-msg $pid close all
imv-msg $pid open "$path"
```

**Comment by eXeC64** [comment]
Directory now exists
