### ISSUE TITLE
keybind confusion

### ISSUE THREAD

**Issue by amanjitsk** [eXeC64/imv#268]
Hi,
I can bind a wallpaper keybind as 
```
<semicolon>w = ...
```
which requires pressing `semicolon` and `w` in succession. But I can't do the same
with `W` (`semicolon` followed by an uppercase alphabet). So for example, I have tried
```
<semicolon>W = ..
<semicolon><Shift+w> = ...
<semicolon><Shift+W> = ...
```
and none of these options work.
I just really want to bind `semicolon` and `W` in succession to some action.

Thanks!

**Comment by eXeC64** [comment]
Thanks for the report. This was the result of a bug, which I've fixed in 0131ab6. It'll be fixed in the next release of imv. The bind syntax that you'll want here is: `<semicolon><Shift+W> = ...`
