### ISSUE TITLE
If a config comments exceeds 200 chars, program wont run 

### ISSUE THREAD

**Issue by freed00m** [eXeC64/imv#270]
Please make config be parseable if comments have more than 200 characters.

Following fails
```
[binds]
# Delete and then close an open image by pressing 'X'
# $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used 

<Shift+D> = exec trash-put "$imv_current_file"; close
```
Delete "used" on the 4th line and program will run
```
[binds]
# Delete and then close an open image by pressing 'X'
# $XDG_DATA_HOME defines the base directory relative to which user specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used 

<Shift+D> = exec trash-put "$imv_current_file"; close

```

**Comment by st4ll1** [comment]
Its not just a comment that does not work if the line exceeds 200 characters.
The ini file parsing defines 200 as maximums for a line.

I would just split the comment into multiple lines, since i think its is easier to read anyways.

If you dont like it you could fix this easily with changing this the following line:

src/ini.h:103
``` c
#define INI_MAX_LINE 200
```

**Comment by freed00m** [comment]
@st4ll1 fine, I am ok with it. But some error message abou line exceeded length would help.

**Comment by JustinLovinger** [comment]
I ran into this issue while trying to define an `exec` in NixOS Home Manager, thanks to the very long absolute paths of NixOS binarires. The resulting line was `n = exec $TERMINAL --working-directory $(/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/dirname "$imv_current_file") -e /nix/store/ib5vm4lilwqz1fi0bih1q9pj2mndzswz-edit-file.sh $(/nix/store/w9wc0d31p4z93cbgxijws03j5s2c4gyf-coreutils-8.31/bin/basename "$imv_current_file") &`.

I can get around it by creating a separate script, but is there a good reason for this limitation? It seems arbitrary to me, and prone to cause issues.
