### ISSUE TITLE
Please add support for HEIC

### ISSUE THREAD

**Issue by p1otr** [eXeC64/imv#271]
First of all: thanks for imv - it's my default viewer!

Could you add support for [High Efficiency Image File Format](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format)?

**Comment by eXeC64** [comment]
I believe we already support this: https://github.com/eXeC64/imv/blob/master/src/backend_libheif.c

**Comment by p1otr** [comment]
I checked released version only, sorry. It's already in git, thanks!
