### ISSUE TITLE
Support loading PNGs from stdin

### ISSUE THREAD

**Issue by anton-christensen** [eXeC64/imv#274]
It took me a while to figure out that this simply wasn't supported. If it's just not feasible to implement this, it would be nice if this was documented in the readme

**Comment by nycex** [comment]
It does work, you have to use e.g. `cat image.png | imv -`.

**Comment by eXeC64** [comment]
This is supported, as per the example nycex gave.

**Comment by anton-christensen** [comment]
Well, it doesn't work on my machine (ubuntu 20.04). But maybe it's because it's build with libPNG instead of another library? I'm not sure. But here's what i recon:
https://github.com/eXeC64/imv/blob/dd3d60c3f9f12f1ca21c59474564f9b5098dd92c/src/backend_libpng.c#L145-L151
The libPNG backend doesn't define `open_memory`
https://github.com/eXeC64/imv/blob/0131ab6f97a6ea82d3c87c7b59646dcf9a8d68fa/src/imv.c#L958-L967
Which is what's required if I understand the source correctly.
