### ISSUE TITLE
imv man page "-s" ("scaling mode") option doesn't mention "crop" scaling mode

### ISSUE THREAD

**Issue by jaimet** [eXeC64/imv#287]
Just a quick documentation bug:

The [imv man page's documentation for the "scaling mode" ("-s") option](https://github.com/eXeC64/imv/blob/0131ab6f97a6ea82d3c87c7b59646dcf9a8d68fa/doc/imv.1.txt#L59) mentions the "none", "shrink" and "full" scaling modes, but it doesn't mention the[ "crop" scaling mode](https://github.com/eXeC64/imv/blob/0131ab6f97a6ea82d3c87c7b59646dcf9a8d68fa/src/imv.c#L699).

Thank you for writing imv, BTW - it is **much** appreciated.

**Comment by eXeC64** [comment]
Good spot, thanks.
