### ISSUE TITLE
Question: is "line continuation" possible in the config file?

### ISSUE THREAD

**Issue by jaimet** [eXeC64/imv#288]
Hi. Just a quick question: is it possible to use "line continuation" in the config file?

For example, something like:

```
...
overlay_text = "line 1\
line 2"
...
```

Or does the way in which the config file is parsed mean that this is not possible?

Thank you!

**Comment by eXeC64** [comment]
The config file is parsed using [inih](https://github.com/benhoyt/inih), which theoretically supports something like that, but would require work in imv to handle.

This isn't something I'm going to find time to work on myself, but pull requests are welcome from those looking to scratch an itch.
