### ISSUE TITLE
imv launches nothing on wayfire

### ISSUE THREAD

**Issue by snakedye** [eXeC64/imv#292]
the window is completely black.

![image](https://user-images.githubusercontent.com/49378990/99886017-493c1680-2c07-11eb-8a21-17c8d16d652f.png)

**Comment by eXeC64** [comment]
This may have been fixed by #298 - if you're able to build from source, could you please retest?

**Comment by snakedye** [comment]
I can confirm it works with imv-git.

**Comment by eXeC64** [comment]
Glad to hear it, thanks for testing.
