### ISSUE TITLE
dwm doesn't tile imv properly

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#30]
A user sent this screenshot: http://i.imgur.com/jx8RYST.png

We need to figure out why it doesn't tile, and resolve that.

**Comment by eXeC64** [comment]
Installed dwm and did some testing. imv tiled just fine for me.

**Comment by eXeC64** [comment]
See #44 for details

**Comment by ShanaXXII** [comment]
imv-1.2 tiles fine on dwm now :)

**Comment by eXeC64** [comment]
Wonderful! Thanks for the heads up.
