### ISSUE TITLE
imv doesn't compile on Gentoo

### ISSUE THREAD

**Issue by MatthiasCoppens** [eXeC64/imv#300]
`imv` doesn't compile since 82960d3c41601652860843c1040acaf7860d79d0. It complains that `PIPE_BUF` on https://github.com/eXeC64/imv/blob/82960d3c41601652860843c1040acaf7860d79d0/src/imv.c#L748 isn't declared.

**Comment by prj-2501** [comment]
Not on Gentoo but including `limits.h` fixes it for me.

**Comment by MatthiasCoppens** [comment]
Can confirm this fixes it for me too
