### ISSUE TITLE
Images don't resize when toggling fullscreen mode

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#31]
Image viewing is done in two implicit modes, locked, and unlocked. Images start as unlocked, but when the user pans/zooms they are locked. Changing image or resetting the view unlocks it again.

When the window resizes, such as when changing fullscreen mode we should be resizing if unlocked.

**Comment by alekskosiacka** [comment]
Hey,
I'm willing to work on this bug.

**Comment by eXeC64** [comment]
It's all yours.
