### ISSUE TITLE
[Feature request] auto rotate based on EXIF data

### ISSUE THREAD

**Issue by eoli3n** [eXeC64/imv#315]
I used with feh this feature
```
     --auto-rotate                                             
             (optional feature, available in this build) Au‐   
             tomatically rotate images based on EXIF data.     
             Does not alter the image files. 
```
Would be great to have it with imv

**Comment by gnull** [comment]
Looks like this functionality must already be in imv. According to Changelog it was implemented in 2016:

https://github.com/eXeC64/imv/blob/eeaf5e3cb983befd20bc5d706f5b8e7cd321decf/CHANGELOG#L135

It must be a bug if it's not working.

**Comment by gnull** [comment]
Imv can use either freeimage or libjpeg backends to open JPEG files. It will automatically rotate images when it's using freeimage, but not with libjpeg.

I don't know why, but Imv defaults to libjpeg when both are available.

@eoli3n, as a quick hack you can manually disable libjpeg and make it use freeimage. This will enable automatic image rotation. To do that, add these two flags to meson invocation (and follow the rest of building instructions from README like usual):

```sh
meson -D freeimage=enabled -D libjpeg=disabled build
```
