### ISSUE TITLE
-n option doesn't work when reading paths from stdin

### ISSUE THREAD

**Issue by typerslow** [eXeC64/imv#317]
When given an index, `ls | imv -n 3`, it simply ignores it, doesn't give any errors.  When given a path, `ls | imv -n image.png`, it gives an error saying `Invalid starting image: image.png`.

Using imv version 4.2.0

**Comment by n3f4s** [comment]
The issue is that when `imv` handle the `-n` option, when given image path from `stdin`, it hasn't listed all images so it can't find the nth image or the path (given with `-n`).
