### ISSUE TITLE
FreeBSD imv 4.2.0 port error: library 'freeimage' not found

### ISSUE THREAD

**Issue by nunotexbsd** [eXeC64/imv#323]
Hello!

I'm working on update imv FreeBSD [port](https://www.freshports.org/graphics/imv/) from 4.1.0 to 4.2.0 and I found that meson can't find freeimage, the rest of backends compiles ok:

```
FREEIMAGE_LIB_DEPENDS=  libfreeimage.so:graphics/freeimage
FREEIMAGE_MESON_ON=     -Dfreeimage=enabled # ld: error: unable to find library -lfreeimage
FREEIMAGE_MESON_OFF=    -Dfreeimage=disabled
```

[pkg info -l freeimage](https://termbin.com/44qr9)

[meson build log](https://termbin.com/vqg4)

Any hints to fix this?

Thanks,
Nuno Teixeira

**Comment by bsdsx** [comment]
Hello,

I'm not a meson guru but "find_library" is deprecated:

https://mesonbuild.com/Reference-manual.html#find_library

In meson.build, at line 104 replace "library" with "dependency" (with empty array at end) ?

I don't know why only freeimage is a library ?


Regards

**Comment by bsdsx** [comment]
Hello,

May be a freeimage problem:

$ pkg info freeimage libjpeg-turbo pkgconf
freeimage-3.18.0_1
libjpeg-turbo-2.0.6
pkgconf-1.7.3,1

$ pkgconf --modversion libturbojpeg
2.0.6

$ pkgconf --modversion freeimage
Package freeimage was not found in the pkg-config search path.
Perhaps you should add the directory containing `freeimage.pc'
to the PKG_CONFIG_PATH environment variable
Package 'freeimage', required by 'virtual:world', not found

$ pkg info -l libjpeg-turbo | grep '.pc$'
        /usr/local/libdata/pkgconfig/libturbojpeg.pc

$ pkg info -l freeimage | grep '.pc$'
$ echo $?
1


Regards

**Comment by nunotexbsd** [comment]
Hi!

imv 4.1.0 compiles fine with freeimage-3.18.0_1 and pkgconf-1.7.3,1 so it leads to a 4.2.0 bug/problem.

What do you think?

**Comment by bsdsx** [comment]
Hello,

imv 4.1.0 don't use meson and build fine.
imv 4.2.0 use meson but meson don't find freeimage library: build fail.

Could you share your imv/Makefile for imv 4.2.0 ?


Regards

**Comment by nunotexbsd** [comment]
[Makefile](https://termbin.com/l6sq)

**Comment by nunotexbsd** [comment]
> pkgconf --modversion freeimage

It seems that freeimage don't have pkgconf support
https://sourceforge.net/p/freeimage/feature-requests/57/

**Comment by bsdsx** [comment]
Hello,

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=254340

Regards

**Comment by nunotexbsd** [comment]
Hello!

I've tested your patch and now freeimage have pkgconf support and graphics/imv build ok with it.

Nice work!
Thanks,
Nuno Teixeira
