### ISSUE TITLE
Slow zoom speed on large images

### ISSUE THREAD

**Issue by ronandalton** [eXeC64/imv#336]
When viewing a large image, the amount the image zooms in on each zoom command appears to be much smaller than what is seen with smaller sized images. Patch bfd2393f0d9c15ce4df7f86a7f594246b3db6526 was supposed to fix the issue of zooming not being constant but it looks like there are still a few problems.

**Comment by ronandalton** [comment]
It looks like it's because of this line:
https://github.com/eXeC64/imv/blob/deb8b5a86450153b2a8abc3418b6e66691c49896/src/viewport.c#L163
I'm not sure why `scale_factor` is dependent on the ratio of buffer width and image width. The scale factor should only be dependent on `amount`.

**Comment by eXeC64** [comment]
Fixed
