### ISSUE TITLE
Please cut a new release

### ISSUE THREAD

**Issue by Logarithmus** [eXeC64/imv#344]
@eXeC64
I love your project & use it on daily basis with `sway`, since it's the only minimalistic image viewer available with Wayland support.
I see that recently you've been engaged in this project again & finally fixed this very annoying `Not a TIFF or MDI file, bad magic number`. So I'd like to see https://github.com/eXeC64/imv/commit/8d918752078f8b418e7f210aa2e62347d2b43a24 in a new release. Most Linux distro's policy is to build packages for the last release, not `master` branch.

**Comment by eXeC64** [comment]
Done, v4.3.0
