### ISSUE TITLE
Show filename and image # (e.g. 3 of 104) as an overlay

### ISSUE THREAD

**Issue by oniony** [eXeC64/imv#35]
In `feh` I can press `d` to toggle a display where I can see the filename and number as a text overlay on the image. I find this feature really handy and find it painful to use `imv` because of the lack of this feature.

**Comment by eXeC64** [comment]
Oops, this is definitely something I wanted when I first started `imv`. I somehow managed to forget to create an issue for it.

**Comment by eXeC64** [comment]
Complete. New options added are `-d` to show overlay by default and `-e FONT:SIZE` to specify font to use in the overlay. The overlay can be toggled at runtime using the `d` key.
