### ISSUE TITLE
Improvements to use it with terminal file managers like ranger

### ISSUE THREAD

**Issue by joedicastro** [eXeC64/imv#36]
I like `imv` a lot, really, and I want to use it as my default image viewer to use it with `ranger` (actually I'm using it like that already), a terminal file manager, but it lacks of two things that still does not make it ideal for the task, and make me think of return to `sxiv`:

a) An option, it not has to be a default one (`sxiv` and `feh` make this by default), to be able to navigate through all the image files in the current directory even when a unique image file is specified via the command line. Thus, you do not to have to select all the images in a directory to explore all of them and at the same time you still can decide which image you would see first.

b) A thumbnail option (`sxiv` and `feh` have both this option) that allows you to previsualize all the image files in the directory in small thumbnails and navigate through them. The thumbnail mode in `sxiv` is specially handy as you can switch between image mode and thumbnail mode easily.

How you see this? doable?

Thanks for create **imv** anyway :smile:

**Comment by jdiez17** [comment]
a should be a matter of calling `imv_navigator_add_path_recursive` with the base directory of the current image.

We definitely plan to include a thumbnail visualization mode in the future.

**Comment by joedicastro** [comment]
@jdiez17 yeah you are right, the first thing I tried was to use `imv -a -r . image_xx.ext` and it works, but it does not open the `image_xx.ext` file as the first one, it opens the first image file of the directory by alphabetic order. Then I tried now `imv -a image_xx.ext -r .` and it works fine! So, I missed to try that before open the issue! :disappointed: 

Then for rangers users, this would work fine (in `rifle.conf` file): 

`mime ^image, has imv, X, flag f= imv -a "$@" -r .`s

So, first point solved!

**Comment by joedicastro** [comment]
Still there is something strange, it does not show the images in the same order as `sxiv`, `feh` or even a simple `ls`, which is the criteria used to sort the image files before show them when using the recursive search? It not seems a problem with numbers or case-sensitivity...

**Comment by eXeC64** [comment]
No sorting is done internally. Currently the best way to sort images is to provide them in the order you wish to view them via another tool, such as `sort` or `shuf`. I was under the impression `find` had built-in sorting functionality which I would have recommended, but it looks like I was wrong.

Sorting functionality is something that could be added as an additional step. I'm reluctant to give imv too much behaviour in that vein though, as sorting by date/size etc. should really be the job of another unix tool. imv ought to be a dumb image viewer that takes what it's given in the order it's given and displays it simply. Searching and sorting files based on different properties are really the work of other utilities.

**Comment by joedicastro** [comment]
Well, I understand perfectly you reasoning, and support it, 'cause at the end it's the UNIX way of doing things, "Do one thing and do it well" and KISS, and I like that. 

But it send me again back to square one, the point **a** of the issue is now unresolved. Let me explain, I can use another tool to do the sort thing, like `sort`, but as what I need is to sort them alphabetically by their filename (as `sxiv` or `feh` does), a simple `ls` would do the trick. Then, if I do something like this:

`$ ls | imv -i`

I can see the images in the proper order as it should be, but in order to use it with `ranger` or other similar tools, if I do something like this:

`$ ls | imv image_xx.ext -i`

it would show first the desired image and then it would show the rest of the images of the directory sorted, but including again the previous image, then it appears two times and it breaks also the natural sequence. 

And if I try something like:

`$ ls !(image_xx.ext) | imv image_xx.ext -i`

Then the images does not appear two times, because the first one is removed from the initial sorted list, but then the natural order of the sequence is also broken.

As a sort of workaround, the first thing that comes to my mind is to make a little bash/python script to get the index of the desired file from the sorted list, and use the `-n` option to start at the given image index position (but to do that I would have to consider all the file extensions/types supported by `imv` to construct the sorted list ignoring the rest of the files, and change that every time that you add a new image type support).

Some idea to solve this without so much hassle?

**Comment by eXeC64** [comment]
The cleanest solution to this, which also makes sense as a feature is to give n support for being given a path instead of a number, and `imv` starting at the first instance of that path in the input list.

`$ ls | imv -n image_05.png -` would be equivalent to you knowing that `image_05.png` is the third supported item and supplying `-n 3`. The images would be viewed in the order given by `ls` of course.

Would that be useful?

Also, just give `imv`  the option `-` instead of `-i` to denote images are being listed via stdin. `imv` is moving to that to fit with other unix tools more. The man page and usage information are supposed to say as much, but it looks like that got accidentally reverted at some point.

**Comment by joedicastro** [comment]
Yes, that would be very useful! :smile: :+1: 

And yes, `-` is a very extended option between UNIX/Linux tools, and to be frankly, as I read the `-i` in the man page, I did not thought to use it, but is good to know that is implemented and going to be the default.

**Comment by eXeC64** [comment]
Fixed, @joedicastro.

**Comment by beanaroo** [comment]
I thought it might be worth mentioning here for discoverability...

ranger recently included imv in the `open_all_images` option. Meaning no arguments for imv are necessary.
https://github.com/hut/ranger/commit/a9f6a0db59535455739a671e9db9abc2f06051bf

**Comment by eXeC64** [comment]
Neat. I was not aware that had been done.
