### ISSUE TITLE
Hide the mouse cursor when appropriate.

### ISSUE THREAD

**Issue by beanaroo** [eXeC64/imv#37]
I was going through some holiday pictures with my family when I noticed:

* When cycling through a bunch of images, the mouse cursor can get in the way, especially when in fullscreen.
* Now and then you might want to use the mouse cursor, like presentation or panning.

I made some successful changes, but I'm not at all familiar with SDL. 
Hides cursor when drawing/redrawing the window. 
Shows cursor when moving mouse.
````diff
diff --git a/src/main.c b/src/main.c
index 5a9c54c..bcbebd8 100644
--- a/src/main.c
+++ b/src/main.c
@@ -338,6 +338,7 @@ int main(int argc, char** argv)
           imv_viewport_zoom(&view, &ldr, IMV_ZOOM_MOUSE, e.wheel.y);
           break;
         case SDL_MOUSEMOTION:
+          SDL_ShowCursor(SDL_ENABLE);
           if(e.motion.state & SDL_BUTTON_LMASK) {
             imv_viewport_move(&view, e.motion.xrel, e.motion.yrel);
           }
@@ -409,6 +410,7 @@ int main(int argc, char** argv)
     }   
 
     if(view.redraw) {
+      SDL_ShowCursor(SDL_DISABLE);
       if(g_options.solid_bg) {
         SDL_SetRenderDrawColor(renderer,
             g_options.bg_r, g_options.bg_g, g_options.bg_b, 255);
````

**Comment by eXeC64** [comment]
Hi @beanaroo, thanks for the patch.

I tried it out, but it doesn't place nicely with animated gifs, as the cursor is re-hidden every frame.

Hiding the cursor when the mouse isn't being used is a good idea though. I'm about to do a large amount of refactoring of the code to enable loading images in the background, so any changes to the patch will be made immediately obsolete. I'll be sure to add this functionality during the refactoring though, as I do like the feature.
