### ISSUE TITLE
Issues with certain animated GIFs

### ISSUE THREAD

**Issue by SirCmpwn** [eXeC64/imv#4]
Here's an example:

https://sr.ht/cxlZ.gif

**Comment by guiniol** [comment]
This gif renders as blank: http://deptford.tv/about/pics/test.gif

**Comment by eXeC64** [comment]
@guiniol Ah, thanks. That image uses a part of the gif spec I hadn't yet implemented (due to not having any sample images that used it). I'll fix that one along wtih SirCmpwn's test case.

**Comment by guiniol** [comment]
Just my luck, First gif I tried ^^

**Comment by eXeC64** [comment]
I've moved your problem to its own issue (#27) @guiniol
