### ISSUE TITLE
Add `-l` option for listing all open images on exit

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#43]
This is useful for people wishing to use imv as part of a image selection pipeline. They can open a bunch of images, filter out the ones they dislike with `x`, and then hit `q` to quit imv, and the paths of the images they kept will be printed to stdout, one per line.

**Comment by alekskosiacka** [comment]
Can I work on this?

**Comment by eXeC64** [comment]
Sure, go ahead.
