### ISSUE TITLE
Slideshow option.

### ISSUE THREAD

**Issue by whatevsz** [eXeC64/imv#45]
Is there interest in adding a slideshow option?

I propose something super simple like a command line option `-s` that expects an integer argument and just skips to the next image after the specified number of seconds.

Thoughts?

If there is interest, I'd go ahead and try to come up with a solution.

**Comment by eXeC64** [comment]
This is one of those features that I'm not strongly opposed to, but I'm certainly hesitant about. Could you expand upon the use case for this? When would a user need this? For a custom electronic picture frame? As a screensaver of some sort?

I'm just struggling to see when this would be useful where imv would also be the appropriate tool for the job.

**Comment by whatevsz** [comment]
My use case would be something like "Being at a family gathering and showing some images on a projector." I guess I could use a remote to switch between images, but a fixed delay works well in my experience. Electronic picture frame would be another example where this is useful (not for me but in general), as you said.

Right now I'm using feh for this, but if you think this feature could be useful to have imv, I'd give it a go.

**Comment by eXeC64** [comment]
I'll accept it, but if done I think it should behave like this:

* `-t [time]` option to set how long to show each image for
* `t` key binding increases display time by 1 second
* `T` key binding decreases display time by 1 second
* If non-zero, the time left and display time should be shown in the overlay and window title in the form `[display-time-so-far/display-time]`
* A display time of `0` indicates the slideshow is not active

This way, the speed can be adjusted at run-time, and playback even paused, with information about how much time is left.

**Comment by whatevsz** [comment]
That sound good, I will try implementing this as soon as I have some time.

**Comment by rien333** [comment]
Is their currently a way to pause the slideshow?

**Comment by eXeC64** [comment]
There isn't a way to pause slideshows as of yet, but it's something that can go into v4. I'm going to be changing around the commands to make them more friendly, but I've not decided how to structure the slideshow commands, perhaps `slideshow <n>` to start the slideshow with a given duration, +- prefix to adjust the duration, and `slideshow pause` to pause/unpause. `ss` would probably be an alias for `slideshow`

**Comment by rien333** [comment]
I like the current solution! You can do something like:
```
[alias]
pause = slideshow 0
```

**Comment by eXeC64** [comment]
I'm not sure it's possible to create a toggle bind/command without further extensions. Also, it's not documented, but `ss` is a builtin alias for `slideshow` so I do `ss 0` to pause and `ss 3` to resume, which I quite like.

**Comment by rien333** [comment]
@eXeC64 a toggle command. Thanks for all the work that you've been putting into the 4.0 branch! (the round thing is a bit silly, but I don't use decimal places for slideshows anyway. Could be made a little more elegant tho) 

```
toggle = exec ([ $(calc -p "round($imv_slideshow_duration)") -eq "0" ] && imv-msg $imv_pid "ss 2") || imv-msg $imv_pid "ss 0"

```

**Comment by eXeC64** [comment]
Neat! I think it wasn't possible before `$imv_pid`, but with that addition a whole bunch of scripting possibilities have opened up.
