### ISSUE TITLE
Add Additional view mode beside 'actual size' and the default.

### ISSUE THREAD

**Issue by knitori** [eXeC64/imv#54]
As far as I can tell, the default behavior is to resize all images to fit the view port, even if the images are smaller, and the 'actual size' mode doesn't resize at all.

So I would like to request a third mode, where images, that are larger than the view, will be resized to fit and smaller images stay unchanged (but centered, like 'actual size' does for smaller images).

**Comment by eXeC64** [comment]
This sounds reasonable to me.

**Comment by czarkoff** [comment]
Fixed in #79.

**Comment by eXeC64** [comment]
Solved by #77
