### ISSUE TITLE
imv does not respect window manager

### ISSUE THREAD

**Issue by autrimpo** [eXeC64/imv#56]
With the image reload support, I started using imv instead of sxiv to display album art. However, I noticed two things:
- When launching imv, it ignores the split preselect (see [bspwm](https://github.com/baskerville/bspwm) for details) and the window is created in the default position.
- When switching to a workspace with imv, it gets the window focus even if a different window was focused before.

Might be related to SDL as with #6? I will try this with some other SDL programs when I have the time to do so.

If the mentioned problems are unclear (I assume you don't use bspwm) I can make a sxiv/imv comparision webm.

**Comment by eXeC64** [comment]
An example of the correct behaviour, and the incorrect behaviour and how to reproduce it would be most helpful for debugging and fixing this issue.

I use i3wm on my machines, but I can install bspwm for testing.

**Comment by autrimpo** [comment]
[Example](https://a.pomf.cat/odkhkv.webm)
Hope this helps, shows both sxiv and imv.

**Comment by shaggytwodope** [comment]
I've never had the issue with focus, using bspwm 0.9-2 and imv 1.2.0-1 on archlinux. But it does ignore the selective split feature. 

Typically the command for this is something like:

```
super + ctrl + {Left,Down,Up,Right}
        bspc window -p {left,down,up,right}
```

When I want imv to open to the right of the current window for example, it'll spawn taking over the current window space, rather then where I want.

**Comment by eXeC64** [comment]
Thanks for the video. That is odd behaviour.

It'd add some complexity, but a possible approach would be detecting whether imv is running on X11 or Wayland and setting the window properties as needed using the relevant native library. SDL provides some APIs for doing that, so in theory it's possible, but I'm reluctant to add that complexity to imv unless it's necessary.

Before considering doing that though, I'd like to nail down what exactly is causing the behaviour. My suspicion is an xprop of some kind.

**Comment by Krak-n** [comment]
Since I'm not 100% sure whether or not this problem needs it's own issue:

While using bspwm, I am unable to set my wallpaper using imv. I can break it down into 2 main issues:

1. I am able to close my wallpaper.

**Comment by Krak-n** [comment]
While using bspwm, I am unable to set my wallpaper using imv:

1. I am able to close my wallpaper. I am able to close the sdl window that is displaying my background after clicking on my background. (using sxhkd)

2. imv occasionally forces itself into the foreground of my desktop, and the sdl window starts to be managed by bspwm.

Semi-related:

Why doesn't feh get affected by the "closing my wallpaper" bug? Using:

    feh --bg-scale $image

Prevents me from closing/managing the feh "window". (is it a window in --bg mode?)

**Comment by eXeC64** [comment]
Could someone affected by this confirm whether it's still an issue please? imv has had a big refactor recently, and several bugs fixed.

**Comment by krakn** [comment]
I'll check in a few.

**Comment by krakn** [comment]
@eXeC64 

It's confirmed still ignoring the preselect.

**Comment by autrimpo** [comment]
I can confirm this as well.

A thing of interest I've noticed: It seems like there's several windows being created in quick succession. Using bspwm's 'external_rules' feature (which runs a script on every new window created) and logging the events gives this output: (I opened termite and then imv)
```
id 85983235
class Termite
inst termite
title termite
id 85983237
class imv
inst imv
title imv
id 85983239
class imv
inst imv
title imv
id 85983242
class imv
inst imv
title imv
```

As you can see, three windows (with different ids) are being created, thus the first one "eats" the preselect and the third one, the actual imv window, ends up using the default split.

**Comment by eXeC64** [comment]
Good detective work there autrimpo. That's extremely strange behaviour. The window creation is all handled inside https://github.com/eXeC64/imv/blob/master/src/imv.c#L534-L595 - if you're able to reproduce it with a minimal program containing just that logic, I'd strongly urge reporting this upstream to SDL2.

**Comment by autrimpo** [comment]
I've narrowed the source of the issue and reported it upstream:
https://bugzilla.libsdl.org/show_bug.cgi?id=3936

**Comment by autrimpo** [comment]
I think we can close this since it's actually an OpenGL limitation, thus won't be fixed.
