### ISSUE TITLE
Support configuration files

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#57]
We should support a basic ini-style config file for our options.

We can use this to parse the ini file: https://github.com/eXeC64/ini_parser

And SirCmpwn has kindly donated [this function](https://github.com/SirCmpwn/sway/blob/master/sway/config.c#L133-L166) to imv under CC0, so we can use that to locate the config file.

I suggest the configuration format look something (this isn't a hard spec) like this:

``` ini
[display]
background = solid
background_color = #000000

[input]
mwheelup = zoom 1
mwheeldown = zoom -1
h = pan -1 0
j = pan 0 1
k = pan 0 -1
l = pan 1 0
left = previous
right = next
```

**Comment by ShanaXXII** [comment]
Is it possible to add an option to tell imv how big to spawn windows? e.g. (1600x900 pixels)
This can be in the form of an option in a configuration file or a command line argument.

**Comment by eXeC64** [comment]
Yeah, that would be useful. I still want to add this, I've just been rather busy lately so haven't found the time to implement it.

**Comment by SirCmpwn** [comment]
bump

**Comment by eXeC64** [comment]
Config file support has been added
