### ISSUE TITLE
Unknown argument 's'

### ISSUE THREAD

**Issue by Krak-n** [eXeC64/imv#61]
Running:

    imv -fs path/to/image.jpg

Results in the error:

    Unknown argument 's'. Aborting.

Installed from the Arch Linux AUR. I'll Give things a quick look in the repository here, but I'm not confident enough in my programming to actually know what exactly will fix this. Possibly the '-s' option not even existing?

**Comment by eXeC64** [comment]
Oops. The `-s` option doesn't actually exist any more but it was left behind in the usage examples. I'll fix those now.

**Comment by Krak-n** [comment]
Is there any "scale" option? Say I had an image that was slightly
larger/smaller than my screen size and I need it scaled to fit the screen.

**Comment by eXeC64** [comment]
Scaling to fit the window is the default mode in imv. If you want the
actual size you can use the -a flag or press a in imv
