### ISSUE TITLE
Can't open file if last line is missing '\n'

### ISSUE THREAD

**Issue by rosswhitfield** [eXeC64/imv#75]
Taking the pbm example from [wikipedia](https://en.wikipedia.org/wiki/Netpbm_format#PBM_example) (included [j.txt](https://github.com/eXeC64/imv/files/81666/j.txt)), if you don't include the newline character on the last line then `imv j.txt` just returns with the message `No input files left. Exiting.` Other image viewers I tried (sxiv, xv, mirage) can open this file.

**Comment by eXeC64** [comment]
This is a tricky one. imv doesn't actually handle any of the format parsing itself; that's done by FreeImage, whereas a lot of other viewers appear to use imlib2.

The best solution is probably to either submit this as a bug to FreeImage, or send FreeImage a patch to fix it. I'm more inclined to doing the latter, as it's better for everyone all round.

**Comment by czarkoff** [comment]
It is not a bug. Pbm files are pixel content encapsulated in text file, and POSIX requires that text files end with newline character. Thus file containing pbm data *must* have a new line.

**Comment by eXeC64** [comment]
If this presents an real-world problem, I recommend reaching out to the FreeImage devs.
