### ISSUE TITLE
View directory from ranger

### ISSUE THREAD

**Issue by DerVerruckteFuchs** [eXeC64/imv#80]
When selecting an image in ranger, by pressing the right arrow key, feh allows viewing of other images in the same directory when rc.conf has the line `set open_all_images true` in it. However with imv, only the single image gets displayed with imv. It would be nice if imv could do this automatically.

I'm not sure if this is specifically an imv thing or that ranger needs to add support for imv.

**Comment by czarkoff** [comment]
Please see the issue #36. Apparently the fix will be shipped in next ranger release.

**Comment by DerVerruckteFuchs** [comment]
I installed ranger-git from the AUR, and the new fixes sort this out. It'll be nice when the next release rolls out. I might stick with ranger-git until then since I need the image viewing functionality.
