### ISSUE TITLE
Add option to exit after all files are processed.

### ISSUE THREAD

**Issue by whatevsz** [eXeC64/imv#84]
As far as I can see, `imv` always cycles through the file list when reaching its end. I propose an option to make `imv` exit when the end of the file list is reached, either by the user pressing the "next" key or by the slideshow automatic.

This might come in handy when calling `imv` from scripts. 

I'm not sure what switch to use for this, maybe `-o` for "once"?

If there is interest, I'd implement the change and issue a pull request.

**Comment by eXeC64** [comment]
This sounds reasonable to me. Feel free to implement it.

I'm not sure what a good switch would be either. o, Q, q, X, and x all seem like reasonable choices.
