### ISSUE TITLE
Linking fails on Fedora 22

### ISSUE THREAD

**Issue by sjkingo** [eXeC64/imv#9]
Trying to compile and link imv on Fedora 22 and getting the following compiler and linker error:

```
imv/ $ make
COMPILING build/texture.o
COMPILING build/viewport.o
COMPILING build/main.o
COMPILING build/image.o
src/image.c: In function ‘imv_image_load_next_frame’:
src/image.c:163:26: warning: implicit declaration of function ‘FreeImage_EnlargeCanvas’ [-Wimplicit-function-declaration]
     FIBITMAP *expanded = FreeImage_EnlargeCanvas(frame32,
                          ^
src/image.c:163:26: warning: initialization makes pointer from integer without a cast [-Wint-conversion]
COMPILING build/navigator.o
LINKING imv
build/image.o: In function `imv_image_load_next_frame':
image.c:(.text+0x5c2): undefined reference to `FreeImage_EnlargeCanvas'
collect2: error: ld returned 1 exit status
Makefile:19: recipe for target 'imv' failed
make: *** [imv] Error 1
```

I have the freeimage headers installed, version 3.10.0-23:

```
imv/ $ rpm -qa | grep freeimage
freeimage-3.10.0-23.fc22.x86_64
freeimage-devel-3.10.0-23.fc22.x86_64
```

Do you have any idea as to what the problem could be?

Thanks

**Comment by jdiez17** [comment]
`FreeImage_EnlargeCanvas` was added in version 3.13.0, so you need to upgrade freeimage. We use it to composite some types of gifs, so it's not a feature we can do without. Perhaps it would be a good idea to provide our own EnlargeCanvas function. Thoughts, @eXeC64?

**Comment by eXeC64** [comment]
I didn't realise it was such a recent feature. Given that F22 was only released in May I think we should be supporting it. We'll just have to re-implement it.

**Comment by sjkingo** [comment]
According to the [release announcement for 3.13.0](http://sourceforge.net/p/freeimage/mailman/message/23629935/), `FreeImage_AllocateEx` was added in this version also, along with `FreeImage_EnlargeCanvas`, so the build still does not work against Fedora 22's freeimage-3.10:

```
build/image.o: In function `imv_image_load_next_frame':
image.c:(.text+0x581): undefined reference to `FreeImage_AllocateEx'
collect2: error: ld returned 1 exit status
```

I will see what version of freeimage is in the F23 repos and report back: perhaps you could just pin the minimum version of freeimage to 3.13.0 if it's in the newer repo.

**Comment by eXeC64** [comment]
Good grief. FreeImage v3.13.0 has been out for 6 years already, and Fedora 22 is shipping an older version than that? Seems that v3.10.0 was released in 2007, making it 8 years old.

I'm not holding out much hope for Fedora 23's repositories.

**Comment by eXeC64** [comment]
@sjkingo I've just pushed a commit that replaces `AllocateEx` with `Allocate`. If Fedora 22 doesn't have that I'll eat my hat.

**Comment by sjkingo** [comment]
No hat eating required @eXeC64: that works nicely, thank-you.

For reference, F23's main repo has version 3.17.0 of freeimage and freeimage-devel. Looks like the maintainer updated it only recently.

Appreciate the quick fixes!

**Comment by eXeC64** [comment]
Good to hear. :beer:
