### ISSUE TITLE
Rotate image

### ISSUE THREAD

**Issue by eXeC64** [eXeC64/imv#92]
Somehow I've managed to forget about supporting rotating images (in increments of 90 degrees). Not an urgent feature, just a would-be-nice.

Rotations do not need to be saved, and should not involve modifying the file on disk (as some other image viewers do). When an image is selected, the rotation should reset to 0. The user may then hit one of two keys to rotate either +90 or (-90/+270) degrees. Changing image abandons the rotation.

Using `{` and `}` is a possibility, but there's plenty of options to choose from.

**Comment by wokka1** [comment]
Perhaps read from exif to auto-rotate as an option as well?

**Comment by czarkoff** [comment]
@wokka1 imv does it for ages now.

**Comment by SirCmpwn** [comment]
Requesting ability to persist the change.

**Comment by eXeC64** [comment]
Once support for configuration (and custom binds) is enabled, it ought to be trivial to configure imv to rotate the current file using imagemagick upon a keypress. imv already reloads the current file when it changes on disk. That'd provide persistence.

**Comment by SirCmpwn** [comment]
That sounds like a good approach to me.

**Comment by eXeC64** [comment]
imv now supports custom key bindings which can be used to invoke imagemagick

**Comment by gnull** [comment]
> @wokka1 imv does it for ages now

Does it? My imv (v4.2.0) seems to ignore the rotation of JPEG photos. The previews I see in Thunar and the photos I see in Eye of Gnome are rotated properly, but in Imv I see them 90° off.

Is there something I need to do to make Imv read Exif info and rotate image automatically at startup?
