### ISSUE TITLE
Running 'imv -xl' may result in segmentation violation

### ISSUE THREAD

**Issue by czarkoff** [eXeC64/imv#93]
When running `imv` with `-x` switch ("exit when reaching end of file list"), at the end of file list navigator's selection would move *after* the end and remain here. If `-l` switch ("list open files on exit"), `imv` would attempt to list open files, starting with current selection. As current selection at that stage will be after the end of list, `nav->paths[nav->cur_path]`, if interpreted as pointer, will likely point at bogus address. (During my testing `imv` printed out 4,3 Gb of unused memory!)

**Comment by eXeC64** [comment]
That'a a sneaky crash. Did you run `-xl` on a hunch, or as part of regular use?

**Comment by czarkoff** [comment]
I was writing a oneliner function for removing images. When rm started writing torrent of "can't remove *some random garbage*" to stderr I knew I had some work to do.
